package me.withers_overhaul.datagen.fabric;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.block.Block;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

import static me.withers_overhaul.registry.block.ColoredBlocks.*;
import static me.withers_overhaul.registry.block.NaturalBlocks.*;
import static me.withers_overhaul.registry.block.StoneBlocks.*;
import static me.withers_overhaul.registry.block.WoodBlocks.*;
import static net.minecraft.item.Items.*;

public class BlockLootTableGen extends FabricBlockLootTableProvider {
    public BlockLootTableGen(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {

        Block[] blocksThatDropThemselves = {
                // Wood
                MAPLE_LOG, MAPLE_WOOD, STRIPPED_MAPLE_LOG, STRIPPED_MAPLE_WOOD, MAPLE_PLANKS, MAPLE_STAIRS, MAPLE_FENCE, MAPLE_FENCE_GATE, MAPLE_DOOR, MAPLE_TRAPDOOR, MAPLE_BUTTON, MAPLE_PRESSURE_PLATE,
                POPLAR_LOG, POPLAR_WOOD, STRIPPED_POPLAR_LOG, STRIPPED_POPLAR_WOOD, POPLAR_PLANKS, POPLAR_STAIRS, POPLAR_FENCE, POPLAR_FENCE_GATE, POPLAR_DOOR, POPLAR_TRAPDOOR, POPLAR_BUTTON, POPLAR_PRESSURE_PLATE,
                BEECH_LOG, BEECH_WOOD, STRIPPED_BEECH_LOG, STRIPPED_BEECH_WOOD, BEECH_PLANKS, BEECH_STAIRS, BEECH_FENCE, BEECH_FENCE_GATE, BEECH_DOOR, BEECH_TRAPDOOR, BEECH_BUTTON, BEECH_PRESSURE_PLATE,
                HICKORY_LOG, HICKORY_WOOD, STRIPPED_HICKORY_LOG, STRIPPED_HICKORY_WOOD, HICKORY_PLANKS, HICKORY_STAIRS, HICKORY_FENCE, HICKORY_FENCE_GATE, HICKORY_DOOR, HICKORY_TRAPDOOR, HICKORY_BUTTON, HICKORY_PRESSURE_PLATE,
                WALNUT_LOG, WALNUT_WOOD, STRIPPED_WALNUT_LOG, STRIPPED_WALNUT_WOOD, WALNUT_PLANKS, WALNUT_STAIRS, WALNUT_FENCE, WALNUT_FENCE_GATE, WALNUT_DOOR, WALNUT_TRAPDOOR, WALNUT_BUTTON, WALNUT_PRESSURE_PLATE,
                CHESTNUT_LOG, CHESTNUT_WOOD, STRIPPED_CHESTNUT_LOG, STRIPPED_CHESTNUT_WOOD, CHESTNUT_PLANKS, CHESTNUT_STAIRS, CHESTNUT_FENCE, CHESTNUT_FENCE_GATE, CHESTNUT_DOOR, CHESTNUT_TRAPDOOR, CHESTNUT_BUTTON, CHESTNUT_PRESSURE_PLATE,
                CEDAR_LOG, CEDAR_WOOD, STRIPPED_CEDAR_LOG, STRIPPED_CEDAR_WOOD, CEDAR_PLANKS, CEDAR_STAIRS, CEDAR_FENCE, CEDAR_FENCE_GATE, CEDAR_DOOR, CEDAR_TRAPDOOR, CEDAR_BUTTON, CEDAR_PRESSURE_PLATE,
                REDWOOD_LOG, REDWOOD_WOOD, STRIPPED_REDWOOD_LOG, STRIPPED_REDWOOD_WOOD, REDWOOD_PLANKS, REDWOOD_STAIRS, REDWOOD_FENCE, REDWOOD_FENCE_GATE, REDWOOD_DOOR, REDWOOD_TRAPDOOR, REDWOOD_BUTTON, REDWOOD_PRESSURE_PLATE,
                FIR_LOG, FIR_WOOD, STRIPPED_FIR_LOG, STRIPPED_FIR_WOOD, FIR_PLANKS, FIR_STAIRS, FIR_FENCE, FIR_FENCE_GATE, FIR_DOOR, FIR_TRAPDOOR, FIR_BUTTON, FIR_PRESSURE_PLATE,
                HEMLOCK_LOG, HEMLOCK_WOOD, STRIPPED_HEMLOCK_LOG, STRIPPED_HEMLOCK_WOOD, HEMLOCK_PLANKS, HEMLOCK_STAIRS, HEMLOCK_FENCE, HEMLOCK_FENCE_GATE, HEMLOCK_DOOR, HEMLOCK_TRAPDOOR, HEMLOCK_BUTTON, HEMLOCK_PRESSURE_PLATE,
                HOLLY_LOG, HOLLY_WOOD, STRIPPED_HOLLY_LOG, STRIPPED_HOLLY_WOOD, HOLLY_PLANKS, HOLLY_STAIRS, HOLLY_FENCE, HOLLY_FENCE_GATE, HOLLY_DOOR, HOLLY_TRAPDOOR, HOLLY_BUTTON, HOLLY_PRESSURE_PLATE,
                PINE_LOG, PINE_WOOD, STRIPPED_PINE_LOG, STRIPPED_PINE_WOOD, PINE_PLANKS, PINE_STAIRS, PINE_FENCE, PINE_FENCE_GATE, PINE_DOOR, PINE_TRAPDOOR, PINE_BUTTON, PINE_PRESSURE_PLATE,
                LARCH_LOG, LARCH_WOOD, STRIPPED_LARCH_LOG, STRIPPED_LARCH_WOOD, LARCH_PLANKS, LARCH_STAIRS, LARCH_FENCE, LARCH_FENCE_GATE, LARCH_DOOR, LARCH_TRAPDOOR, LARCH_BUTTON, LARCH_PRESSURE_PLATE,
                ASPEN_LOG, ASPEN_WOOD, STRIPPED_ASPEN_LOG, STRIPPED_ASPEN_WOOD, ASPEN_PLANKS, ASPEN_STAIRS, ASPEN_FENCE, ASPEN_FENCE_GATE, ASPEN_DOOR, ASPEN_TRAPDOOR, ASPEN_BUTTON, ASPEN_PRESSURE_PLATE,
                KAPOK_LOG, KAPOK_WOOD, STRIPPED_KAPOK_LOG, STRIPPED_KAPOK_WOOD, KAPOK_PLANKS, KAPOK_STAIRS, KAPOK_FENCE, KAPOK_FENCE_GATE, KAPOK_DOOR, KAPOK_TRAPDOOR, KAPOK_BUTTON, KAPOK_PRESSURE_PLATE,
                MAHOGANY_LOG, MAHOGANY_WOOD, STRIPPED_MAHOGANY_LOG, STRIPPED_MAHOGANY_WOOD, MAHOGANY_PLANKS, MAHOGANY_STAIRS, MAHOGANY_FENCE, MAHOGANY_FENCE_GATE, MAHOGANY_DOOR, MAHOGANY_TRAPDOOR, MAHOGANY_BUTTON, MAHOGANY_PRESSURE_PLATE,
                EUCALYPTUS_LOG, EUCALYPTUS_WOOD, STRIPPED_EUCALYPTUS_LOG, STRIPPED_EUCALYPTUS_WOOD, EUCALYPTUS_PLANKS, EUCALYPTUS_STAIRS, EUCALYPTUS_FENCE, EUCALYPTUS_FENCE_GATE, EUCALYPTUS_DOOR, EUCALYPTUS_TRAPDOOR, EUCALYPTUS_BUTTON, EUCALYPTUS_PRESSURE_PLATE,
                BAOBAB_LOG, BAOBAB_WOOD, STRIPPED_BAOBAB_LOG, STRIPPED_BAOBAB_WOOD, BAOBAB_PLANKS, BAOBAB_STAIRS, BAOBAB_FENCE, BAOBAB_FENCE_GATE, BAOBAB_DOOR, BAOBAB_TRAPDOOR, BAOBAB_BUTTON, BAOBAB_PRESSURE_PLATE,
                PALO_VERDE_LOG, PALO_VERDE_WOOD, STRIPPED_PALO_VERDE_LOG, STRIPPED_PALO_VERDE_WOOD, PALO_VERDE_PLANKS, PALO_VERDE_STAIRS, PALO_VERDE_FENCE, PALO_VERDE_FENCE_GATE, PALO_VERDE_DOOR, PALO_VERDE_TRAPDOOR, PALO_VERDE_BUTTON, PALO_VERDE_PRESSURE_PLATE,
                JOSHUA_LOG, JOSHUA_WOOD, STRIPPED_JOSHUA_LOG, STRIPPED_JOSHUA_WOOD, JOSHUA_PLANKS, JOSHUA_STAIRS, JOSHUA_FENCE, JOSHUA_FENCE_GATE, JOSHUA_DOOR, JOSHUA_TRAPDOOR, JOSHUA_BUTTON, JOSHUA_PRESSURE_PLATE,
                JUNIPER_LOG, JUNIPER_WOOD, STRIPPED_JUNIPER_LOG, STRIPPED_JUNIPER_WOOD, JUNIPER_PLANKS, JUNIPER_STAIRS, JUNIPER_FENCE, JUNIPER_FENCE_GATE, JUNIPER_DOOR, JUNIPER_TRAPDOOR, JUNIPER_BUTTON, JUNIPER_PRESSURE_PLATE,
                PALM_LOG, PALM_WOOD, STRIPPED_PALM_LOG, STRIPPED_PALM_WOOD, PALM_PLANKS, PALM_STAIRS, PALM_FENCE, PALM_FENCE_GATE, PALM_DOOR, PALM_TRAPDOOR, PALM_BUTTON, PALM_PRESSURE_PLATE,
                EBONY_LOG, EBONY_WOOD, STRIPPED_EBONY_LOG, STRIPPED_EBONY_WOOD, EBONY_PLANKS, EBONY_STAIRS, EBONY_FENCE, EBONY_FENCE_GATE, EBONY_DOOR, EBONY_TRAPDOOR, EBONY_BUTTON, EBONY_PRESSURE_PLATE,
                TEAK_LOG, TEAK_WOOD, STRIPPED_TEAK_LOG, STRIPPED_TEAK_WOOD, TEAK_PLANKS, TEAK_STAIRS, TEAK_FENCE, TEAK_FENCE_GATE, TEAK_DOOR, TEAK_TRAPDOOR, TEAK_BUTTON, TEAK_PRESSURE_PLATE,
                ELM_LOG, ELM_WOOD, STRIPPED_ELM_LOG, STRIPPED_ELM_WOOD, ELM_PLANKS, ELM_STAIRS, ELM_FENCE, ELM_FENCE_GATE, ELM_DOOR, ELM_TRAPDOOR, ELM_BUTTON, ELM_PRESSURE_PLATE,
                WILLOW_LOG, WILLOW_WOOD, STRIPPED_WILLOW_LOG, STRIPPED_WILLOW_WOOD, WILLOW_PLANKS, WILLOW_STAIRS, WILLOW_FENCE, WILLOW_FENCE_GATE, WILLOW_DOOR, WILLOW_TRAPDOOR, WILLOW_BUTTON, WILLOW_PRESSURE_PLATE,
                CYPRESS_LOG, CYPRESS_WOOD, STRIPPED_CYPRESS_LOG, STRIPPED_CYPRESS_WOOD, CYPRESS_PLANKS, CYPRESS_STAIRS, CYPRESS_FENCE, CYPRESS_FENCE_GATE, CYPRESS_DOOR, CYPRESS_TRAPDOOR, CYPRESS_BUTTON, CYPRESS_PRESSURE_PLATE,
                SAKURA_LOG, SAKURA_WOOD, STRIPPED_SAKURA_LOG, STRIPPED_SAKURA_WOOD, SAKURA_PLANKS, SAKURA_STAIRS, SAKURA_FENCE, SAKURA_FENCE_GATE, SAKURA_DOOR, SAKURA_TRAPDOOR, SAKURA_BUTTON, SAKURA_PRESSURE_PLATE,
                MAGNOLIA_LOG, MAGNOLIA_WOOD, STRIPPED_MAGNOLIA_LOG, STRIPPED_MAGNOLIA_WOOD, MAGNOLIA_PLANKS, MAGNOLIA_STAIRS, MAGNOLIA_FENCE, MAGNOLIA_FENCE_GATE, MAGNOLIA_DOOR, MAGNOLIA_TRAPDOOR, MAGNOLIA_BUTTON, MAGNOLIA_PRESSURE_PLATE,
                JACARANDA_LOG, JACARANDA_WOOD, STRIPPED_JACARANDA_LOG, STRIPPED_JACARANDA_WOOD, JACARANDA_PLANKS, JACARANDA_STAIRS, JACARANDA_FENCE, JACARANDA_FENCE_GATE, JACARANDA_DOOR, JACARANDA_TRAPDOOR, JACARANDA_BUTTON, JACARANDA_PRESSURE_PLATE,
                // Stone
                STONE_WALL, SMOOTH_STONE_STAIRS, SMOOTH_STONE_WALL, STONE_BRICK_PILLAR,
                POLISHED_GRANITE_WALL, GRANITE_BRICKS, CRACKED_GRANITE_BRICKS, GRANITE_BRICK_STAIRS, GRANITE_BRICK_WALL, MOSSY_GRANITE_BRICKS, MOSSY_GRANITE_BRICK_STAIRS, MOSSY_GRANITE_BRICK_WALL, GRANITE_BRICK_PILLAR, CHISELED_GRANITE_BRICKS, POLISHED_GRANITE_BUTTON, POLISHED_GRANITE_PRESSURE_PLATE,
                POLISHED_DIORITE_WALL, DIORITE_BRICKS, CRACKED_DIORITE_BRICKS, DIORITE_BRICK_STAIRS, DIORITE_BRICK_WALL, MOSSY_DIORITE_BRICKS, MOSSY_DIORITE_BRICK_STAIRS, MOSSY_DIORITE_BRICK_WALL, DIORITE_BRICK_PILLAR, CHISELED_DIORITE_BRICKS, POLISHED_DIORITE_BUTTON, POLISHED_DIORITE_PRESSURE_PLATE,
                POLISHED_ANDESITE_WALL, ANDESITE_BRICKS, CRACKED_ANDESITE_BRICKS, ANDESITE_BRICK_STAIRS, ANDESITE_BRICK_WALL, MOSSY_ANDESITE_BRICKS, MOSSY_ANDESITE_BRICK_STAIRS, MOSSY_ANDESITE_BRICK_WALL, ANDESITE_BRICK_PILLAR, CHISELED_ANDESITE_BRICKS, POLISHED_ANDESITE_BUTTON, POLISHED_ANDESITE_PRESSURE_PLATE,
                GNEISS, GNEISS_STAIRS, GNEISS_WALL, POLISHED_GNEISS, POLISHED_GNEISS_STAIRS, POLISHED_GNEISS_WALL, GNEISS_BRICKS, CRACKED_GNEISS_BRICKS, GNEISS_BRICK_STAIRS, GNEISS_BRICK_WALL, MOSSY_GNEISS_BRICKS, MOSSY_GNEISS_BRICK_STAIRS, MOSSY_GNEISS_BRICK_WALL, GNEISS_BRICK_PILLAR, CHISELED_GNEISS_BRICKS, POLISHED_GNEISS_BUTTON, POLISHED_GNEISS_PRESSURE_PLATE,
                SHALE, SHALE_STAIRS, SHALE_WALL, POLISHED_SHALE, POLISHED_SHALE_STAIRS, POLISHED_SHALE_WALL, SHALE_BRICKS, CRACKED_SHALE_BRICKS, SHALE_BRICK_STAIRS, SHALE_BRICK_WALL, MOSSY_SHALE_BRICKS, MOSSY_SHALE_BRICK_STAIRS, MOSSY_SHALE_BRICK_WALL, SHALE_BRICK_PILLAR, CHISELED_SHALE_BRICKS, POLISHED_SHALE_BUTTON, POLISHED_SHALE_PRESSURE_PLATE,
                MARBLE, MARBLE_STAIRS, MARBLE_WALL, POLISHED_MARBLE, POLISHED_MARBLE_STAIRS, POLISHED_MARBLE_WALL, MARBLE_BRICKS, CRACKED_MARBLE_BRICKS, MARBLE_BRICK_STAIRS, MARBLE_BRICK_WALL, MOSSY_MARBLE_BRICKS, MOSSY_MARBLE_BRICK_STAIRS, MOSSY_MARBLE_BRICK_WALL, MARBLE_BRICK_PILLAR, CHISELED_MARBLE_BRICKS, POLISHED_MARBLE_BUTTON, POLISHED_MARBLE_PRESSURE_PLATE,
                GABBRO, GABBRO_STAIRS, GABBRO_WALL, POLISHED_GABBRO, POLISHED_GABBRO_STAIRS, POLISHED_GABBRO_WALL, GABBRO_BRICKS, CRACKED_GABBRO_BRICKS, GABBRO_BRICK_STAIRS, GABBRO_BRICK_WALL, MOSSY_GABBRO_BRICKS, MOSSY_GABBRO_BRICK_STAIRS, MOSSY_GABBRO_BRICK_WALL, GABBRO_BRICK_PILLAR, CHISELED_GABBRO_BRICKS, POLISHED_GABBRO_BUTTON, POLISHED_GABBRO_PRESSURE_PLATE,
                PHYLLITE, PHYLLITE_STAIRS, PHYLLITE_WALL, POLISHED_PHYLLITE, POLISHED_PHYLLITE_STAIRS, POLISHED_PHYLLITE_WALL, PHYLLITE_BRICKS, CRACKED_PHYLLITE_BRICKS, PHYLLITE_BRICK_STAIRS, PHYLLITE_BRICK_WALL, MOSSY_PHYLLITE_BRICKS, MOSSY_PHYLLITE_BRICK_STAIRS, MOSSY_PHYLLITE_BRICK_WALL, PHYLLITE_BRICK_PILLAR, CHISELED_PHYLLITE_BRICKS, POLISHED_PHYLLITE_BUTTON, POLISHED_PHYLLITE_PRESSURE_PLATE,
                CRACKED_TUFF_BRICKS,
                CALCITE_STAIRS, CALCITE_WALL, POLISHED_CALCITE, POLISHED_CALCITE_STAIRS, CALCITE_BRICKS, CALCITE_BRICK_STAIRS, CALCITE_BRICK_WALL, CHISELED_CALCITE,
                DRIPSTONE_STAIRS, DRIPSTONE_WALL, POLISHED_DRIPSTONE, POLISHED_DRIPSTONE_STAIRS, POLISHED_DRIPSTONE_WALL, DRIPSTONE_BRICKS, DRIPSTONE_BRICK_STAIRS, DRIPSTONE_BRICK_WALL, CHISELED_DRIPSTONE,
                CRACKED_BRICKS, CRACKED_MUD_BRICKS, CHISELED_MUD_BRICKS,
                CUT_SANDSTONE_STAIRS, CUT_SANDSTONE_WALL, SMOOTH_SANDSTONE_WALL, ROUGH_SANDSTONE, ROUGH_SANDSTONE_STAIRS, ROUGH_SANDSTONE_WALL,
                CUT_RED_SANDSTONE_STAIRS, CUT_RED_SANDSTONE_WALL, SMOOTH_RED_SANDSTONE_WALL, ROUGH_RED_SANDSTONE, ROUGH_RED_SANDSTONE_STAIRS, ROUGH_RED_SANDSTONE_WALL,
                FROSTED_SANDSTONE, FROSTED_SANDSTONE_STAIRS, FROSTED_SANDSTONE_WALL, CHISELED_FROSTED_SANDSTONE, CUT_FROSTED_SANDSTONE, CUT_FROSTED_SANDSTONE_STAIRS, CUT_FROSTED_SANDSTONE_WALL, SMOOTH_FROSTED_SANDSTONE, SMOOTH_FROSTED_SANDSTONE_STAIRS, SMOOTH_FROSTED_SANDSTONE_WALL, ROUGH_FROSTED_SANDSTONE, ROUGH_FROSTED_SANDSTONE_STAIRS, ROUGH_FROSTED_SANDSTONE_WALL,
                CHARRED_SANDSTONE, CHARRED_SANDSTONE_STAIRS, CHARRED_SANDSTONE_WALL, CHISELED_CHARRED_SANDSTONE, CUT_CHARRED_SANDSTONE, CUT_CHARRED_SANDSTONE_STAIRS, CUT_CHARRED_SANDSTONE_WALL, SMOOTH_CHARRED_SANDSTONE, SMOOTH_CHARRED_SANDSTONE_STAIRS, SMOOTH_CHARRED_SANDSTONE_WALL, ROUGH_CHARRED_SANDSTONE, ROUGH_CHARRED_SANDSTONE_STAIRS, ROUGH_CHARRED_SANDSTONE_WALL,
                CRACKED_PRISMARINE_BRICKS, PRISMARINE_BRICK_WALL, DARK_PRISMARINE_WALL, CHISELED_PRISMARINE_BRICKS,
                CRACKED_RED_NETHER_BRICKS, RED_NETHER_BRICK_FENCE, CHISELED_RED_NETHER_BRICKS, BLUE_NETHER_BRICKS, CRACKED_BLUE_NETHER_BRICKS, BLUE_NETHER_BRICK_STAIRS, BLUE_NETHER_BRICK_WALL, BLUE_NETHER_BRICK_FENCE, CHISELED_BLUE_NETHER_BRICKS,
                QUARTZ_WALL, CRACKED_QUARTZ_BRICKS, QUARTZ_BRICK_STAIRS, QUARTZ_BRICK_WALL, SMOOTH_QUARTZ_WALL,
                AMETHYST_STAIRS, AMETHYST_WALL, AMETHYST_BRICKS, AMETHYST_BRICK_STAIRS, AMETHYST_BRICK_WALL, AMETHYST_TILES, AMETHYST_TILE_STAIRS, AMETHYST_TILE_WALL, CHISELED_AMETHYST,
                DOLOMITE, DOLOMITE_STAIRS, DOLOMITE_WALL, DOLOMITE_BRICKS, DOLOMITE_BRICK_STAIRS, DOLOMITE_BRICK_WALL, DOLOMITE_TILES, DOLOMITE_TILE_STAIRS, DOLOMITE_TILE_WALL, CHISELED_DOLOMITE,
                GYPSUM, GYPSUM_STAIRS, GYPSUM_WALL, GYPSUM_BRICKS, GYPSUM_BRICK_STAIRS, GYPSUM_TILES, GYPSUM_TILE_STAIRS, GYPSUM_TILE_WALL, CHISELED_GYPSUM,
                // Colored Blocks
                WHITE_CONCRETE_STAIRS, WHITE_CONCRETE_WALL,
                LIGHT_GRAY_CONCRETE_STAIRS, LIGHT_GRAY_CONCRETE_WALL,
                GRAY_CONCRETE_STAIRS, GRAY_CONCRETE_WALL,
                BLACK_CONCRETE_STAIRS, BLACK_CONCRETE_WALL,
                BROWN_CONCRETE_STAIRS, BROWN_CONCRETE_WALL,
                RED_CONCRETE_STAIRS, RED_CONCRETE_WALL,
                ORANGE_CONCRETE_STAIRS, ORANGE_CONCRETE_WALL,
                YELLOW_CONCRETE_STAIRS, YELLOW_CONCRETE_WALL,
                LIME_CONCRETE_STAIRS, LIME_CONCRETE_WALL,
                GREEN_CONCRETE_STAIRS, GREEN_CONCRETE_WALL,
                CYAN_CONCRETE_STAIRS, CYAN_CONCRETE_WALL,
                LIGHT_BLUE_CONCRETE_STAIRS, LIGHT_BLUE_CONCRETE_WALL,
                BLUE_CONCRETE_STAIRS, BLUE_CONCRETE_WALL,
                PURPLE_CONCRETE_STAIRS, PURPLE_CONCRETE_WALL,
                MAGENTA_CONCRETE_STAIRS, MAGENTA_CONCRETE_WALL,
                PINK_CONCRETE_STAIRS, PINK_CONCRETE_WALL,
                TERRACOTTA_STAIRS, TERRACOTTA_WALL, TERRACOTTA_BRICKS, TERRACOTTA_BRICK_STAIRS,
                WHITE_TERRACOTTA_STAIRS, WHITE_TERRACOTTA_WALL, WHITE_TERRACOTTA_BRICKS, WHITE_TERRACOTTA_BRICK_STAIRS, WHITE_TERRACOTTA_BRICK_WALL,
                LIGHT_GRAY_TERRACOTTA_STAIRS, LIGHT_GRAY_TERRACOTTA_WALL, LIGHT_GRAY_TERRACOTTA_BRICKS, LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS, LIGHT_GRAY_TERRACOTTA_BRICK_WALL,
                GRAY_TERRACOTTA_STAIRS, GRAY_TERRACOTTA_WALL, GRAY_TERRACOTTA_BRICKS, GRAY_TERRACOTTA_BRICK_STAIRS, GRAY_TERRACOTTA_BRICK_WALL,
                BLACK_TERRACOTTA_STAIRS, BLACK_TERRACOTTA_WALL, BLACK_TERRACOTTA_BRICKS, BLACK_TERRACOTTA_BRICK_STAIRS, BLACK_TERRACOTTA_BRICK_WALL,
                BROWN_TERRACOTTA_STAIRS, BROWN_TERRACOTTA_WALL, BROWN_TERRACOTTA_BRICKS, BROWN_TERRACOTTA_BRICK_STAIRS, BROWN_TERRACOTTA_BRICK_WALL,
                RED_TERRACOTTA_STAIRS, RED_TERRACOTTA_WALL, RED_TERRACOTTA_BRICKS, RED_TERRACOTTA_BRICK_STAIRS, RED_TERRACOTTA_BRICK_WALL,
                ORANGE_TERRACOTTA_STAIRS, ORANGE_TERRACOTTA_WALL, ORANGE_TERRACOTTA_BRICKS, ORANGE_TERRACOTTA_BRICK_STAIRS, ORANGE_TERRACOTTA_BRICK_WALL,
                YELLOW_TERRACOTTA_STAIRS, YELLOW_TERRACOTTA_WALL, YELLOW_TERRACOTTA_BRICKS, YELLOW_TERRACOTTA_BRICK_STAIRS, YELLOW_TERRACOTTA_BRICK_WALL,
                LIME_TERRACOTTA_STAIRS, LIME_TERRACOTTA_WALL, LIME_TERRACOTTA_BRICKS, LIME_TERRACOTTA_BRICK_STAIRS, LIME_TERRACOTTA_BRICK_WALL,
                GREEN_TERRACOTTA_STAIRS, GREEN_TERRACOTTA_WALL, GREEN_TERRACOTTA_BRICKS, GREEN_TERRACOTTA_BRICK_STAIRS, GREEN_TERRACOTTA_BRICK_WALL,
                CYAN_TERRACOTTA_STAIRS, CYAN_TERRACOTTA_WALL, CYAN_TERRACOTTA_BRICKS, CYAN_TERRACOTTA_BRICK_STAIRS, CYAN_TERRACOTTA_BRICK_WALL,
                LIGHT_BLUE_TERRACOTTA_STAIRS, LIGHT_BLUE_TERRACOTTA_WALL, LIGHT_BLUE_TERRACOTTA_BRICKS, LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS, LIGHT_BLUE_TERRACOTTA_BRICK_WALL,
                BLUE_TERRACOTTA_STAIRS, BLUE_TERRACOTTA_WALL, BLUE_TERRACOTTA_BRICKS, BLUE_TERRACOTTA_BRICK_STAIRS, BLUE_TERRACOTTA_BRICK_WALL,
                PURPLE_TERRACOTTA_STAIRS, PURPLE_TERRACOTTA_WALL, PURPLE_TERRACOTTA_BRICKS, PURPLE_TERRACOTTA_BRICK_STAIRS, PURPLE_TERRACOTTA_BRICK_WALL,
                MAGENTA_TERRACOTTA_STAIRS, MAGENTA_TERRACOTTA_WALL, MAGENTA_TERRACOTTA_BRICKS, MAGENTA_TERRACOTTA_BRICK_STAIRS, MAGENTA_TERRACOTTA_BRICK_WALL,
                PINK_TERRACOTTA_STAIRS, PINK_TERRACOTTA_WALL, PINK_TERRACOTTA_BRICKS, PINK_TERRACOTTA_BRICK_STAIRS, PINK_TERRACOTTA_BRICK_WALL,
                CHALK, CHALK_STAIRS, CHALK_WALL, CHALK_BRICKS, CHALK_BRICK_STAIRS,
                WHITE_CHALK, WHITE_CHALK_STAIRS, WHITE_CHALK_WALL, WHITE_CHALK_BRICKS, WHITE_CHALK_BRICK_STAIRS, WHITE_CHALK_BRICK_WALL,
                LIGHT_GRAY_CHALK, LIGHT_GRAY_CHALK_STAIRS, LIGHT_GRAY_CHALK_WALL, LIGHT_GRAY_CHALK_BRICKS, LIGHT_GRAY_CHALK_BRICK_STAIRS, LIGHT_GRAY_CHALK_BRICK_WALL,
                GRAY_CHALK, GRAY_CHALK_STAIRS, GRAY_CHALK_WALL, GRAY_CHALK_BRICKS, GRAY_CHALK_BRICK_STAIRS, GRAY_CHALK_BRICK_WALL,
                BLACK_CHALK, BLACK_CHALK_STAIRS, BLACK_CHALK_WALL, BLACK_CHALK_BRICKS, BLACK_CHALK_BRICK_STAIRS, BLACK_CHALK_BRICK_WALL,
                BROWN_CHALK, BROWN_CHALK_STAIRS, BROWN_CHALK_WALL, BROWN_CHALK_BRICKS, BROWN_CHALK_BRICK_STAIRS, BROWN_CHALK_BRICK_WALL,
                RED_CHALK, RED_CHALK_STAIRS, RED_CHALK_WALL, RED_CHALK_BRICKS, RED_CHALK_BRICK_STAIRS, RED_CHALK_BRICK_WALL,
                ORANGE_CHALK, ORANGE_CHALK_STAIRS, ORANGE_CHALK_WALL, ORANGE_CHALK_BRICKS, ORANGE_CHALK_BRICK_STAIRS, ORANGE_CHALK_BRICK_WALL,
                YELLOW_CHALK, YELLOW_CHALK_STAIRS, YELLOW_CHALK_WALL, YELLOW_CHALK_BRICKS, YELLOW_CHALK_BRICK_STAIRS, YELLOW_CHALK_BRICK_WALL,
                LIME_CHALK, LIME_CHALK_STAIRS, LIME_CHALK_WALL, LIME_CHALK_BRICKS, LIME_CHALK_BRICK_STAIRS, LIME_CHALK_BRICK_WALL,
                GREEN_CHALK, GREEN_CHALK_STAIRS, GREEN_CHALK_WALL, GREEN_CHALK_BRICKS, GREEN_CHALK_BRICK_STAIRS, GREEN_CHALK_BRICK_WALL,
                CYAN_CHALK, CYAN_CHALK_STAIRS, CYAN_CHALK_WALL, CYAN_CHALK_BRICKS, CYAN_CHALK_BRICK_STAIRS, CYAN_CHALK_BRICK_WALL,
                LIGHT_BLUE_CHALK, LIGHT_BLUE_CHALK_STAIRS, LIGHT_BLUE_CHALK_WALL, LIGHT_BLUE_CHALK_BRICKS, LIGHT_BLUE_CHALK_BRICK_STAIRS, LIGHT_BLUE_CHALK_BRICK_WALL,
                BLUE_CHALK, BLUE_CHALK_STAIRS, BLUE_CHALK_WALL, BLUE_CHALK_BRICKS, BLUE_CHALK_BRICK_STAIRS, BLUE_CHALK_BRICK_WALL,
                PURPLE_CHALK, PURPLE_CHALK_STAIRS, PURPLE_CHALK_WALL, PURPLE_CHALK_BRICKS, PURPLE_CHALK_BRICK_STAIRS, PURPLE_CHALK_BRICK_WALL,
                MAGENTA_CHALK, MAGENTA_CHALK_STAIRS, MAGENTA_CHALK_WALL, MAGENTA_CHALK_BRICKS, MAGENTA_CHALK_BRICK_STAIRS, MAGENTA_CHALK_BRICK_WALL,
                PINK_CHALK, PINK_CHALK_STAIRS, PINK_CHALK_WALL, PINK_CHALK_BRICKS, PINK_CHALK_BRICK_STAIRS, PINK_CHALK_BRICK_WALL,
                // Natural
                MAPLE_SAPLING, POPLAR_SAPLING, BEECH_SAPLING, HICKORY_SAPLING, WALNUT_SAPLING, CHESTNUT_SAPLING, CEDAR_SAPLING, REDWOOD_SAPLING, FIR_SAPLING, HEMLOCK_SAPLING, HOLLY_SAPLING,
                LARCH_SAPLING, ASPEN_SAPLING, KAPOK_SAPLING, MAHOGANY_SAPLING, EUCALYPTUS_SAPLING, BAOBAB_SAPLING, PALO_VERDE_SAPLING, JOSHUA_SAPLING, JUNIPER_SAPLING,
                PALM_SAPLING, EBONY_SAPLING, TEAK_SAPLING, ELM_SAPLING, WILLOW_SAPLING, CYPRESS_SAPLING, SAKURA_SAPLING, MAGNOLIA_SAPLING, FLOWERING_MAGNOLIA_SAPLING, JACARANDA_SAPLING,
                FROSTED_SAND, CHARRED_SAND, GOURD, CARVED_GOURD, PEAT_BLOCK, LAVENDER
        };

        for (Block blockThatDropsItself : blocksThatDropThemselves) {
            addDrop(blockThatDropsItself, blockThatDropsItself);
        }

        Block[] slabs = {
                // Wooden
                MAPLE_SLAB, POPLAR_SLAB, BEECH_SLAB, HICKORY_SLAB, WALNUT_SLAB, CHESTNUT_SLAB, CEDAR_SLAB, REDWOOD_SLAB, FIR_SLAB, HEMLOCK_SLAB,
                HOLLY_SLAB, PINE_SLAB, LARCH_SLAB, ASPEN_SLAB, KAPOK_SLAB, MAHOGANY_SLAB, EUCALYPTUS_SLAB, BAOBAB_SLAB, PALO_VERDE_SLAB, JOSHUA_SLAB,
                JUNIPER_SLAB, PALM_SLAB, EBONY_SLAB, TEAK_SLAB, ELM_SLAB, WILLOW_SLAB, CYPRESS_SLAB, SAKURA_SLAB, MAGNOLIA_SLAB, JACARANDA_SLAB,
                // Stone
                GRANITE_BRICK_SLAB, MOSSY_GRANITE_BRICK_SLAB, DIORITE_BRICK_SLAB, MOSSY_DIORITE_BRICK_SLAB, ANDESITE_BRICK_SLAB, MOSSY_ANDESITE_BRICK_SLAB,
                GNEISS_SLAB, POLISHED_GNEISS_SLAB, GNEISS_BRICK_SLAB, MOSSY_GNEISS_BRICK_SLAB,
                SHALE_SLAB, POLISHED_SHALE_SLAB, SHALE_BRICK_SLAB, MOSSY_SHALE_BRICK_SLAB,
                LIMESTONE_SLAB, POLISHED_LIMESTONE_SLAB, LIMESTONE_BRICK_SLAB, MOSSY_LIMESTONE_BRICK_SLAB,
                MARBLE_SLAB, POLISHED_MARBLE_SLAB, MARBLE_BRICK_SLAB, MOSSY_MARBLE_BRICK_SLAB,
                GABBRO_SLAB, POLISHED_GABBRO_SLAB, GABBRO_BRICK_SLAB, MOSSY_GABBRO_BRICK_SLAB,
                PHYLLITE_SLAB, POLISHED_PHYLLITE_SLAB, PHYLLITE_BRICK_SLAB, MOSSY_PHYLLITE_BRICK_SLAB,
                CALCITE_SLAB, POLISHED_CALCITE_SLAB, CALCITE_BRICK_SLAB,
                DRIPSTONE_SLAB, POLISHED_DRIPSTONE_SLAB, DRIPSTONE_BRICK_SLAB,
                ROUGH_SANDSTONE_SLAB, ROUGH_RED_SANDSTONE_SLAB,
                FROSTED_SANDSTONE_SLAB, CUT_CHARRED_SANDSTONE_SLAB, SMOOTH_FROSTED_SANDSTONE_SLAB, ROUGH_FROSTED_SANDSTONE_SLAB,
                CHARRED_SANDSTONE_SLAB, CUT_CHARRED_SANDSTONE_SLAB, SMOOTH_CHARRED_SANDSTONE_SLAB, ROUGH_CHARRED_SANDSTONE_SLAB,
                BLUE_NETHER_BRICK_SLAB, QUARTZ_BRICK_SLAB,
                AMETHYST_SLAB, AMETHYST_BRICK_SLAB, AMETHYST_TILE_SLAB,
                DOLOMITE_SLAB, DOLOMITE_BRICK_SLAB, DOLOMITE_TILE_SLAB,
                GYPSUM_SLAB, GYPSUM_BRICK_SLAB, GYPSUM_TILE_SLAB,
                // Colored
                WHITE_CONCRETE_SLAB, LIGHT_GRAY_CONCRETE_SLAB, GRAY_CONCRETE_SLAB, BLACK_CONCRETE_SLAB, BROWN_CONCRETE_SLAB, RED_CONCRETE_SLAB, ORANGE_CONCRETE_SLAB, YELLOW_CONCRETE_SLAB,
                LIME_CONCRETE_SLAB, GREEN_CONCRETE_SLAB, CYAN_CONCRETE_SLAB, LIGHT_BLUE_CONCRETE_SLAB, BLUE_CONCRETE_SLAB, PURPLE_CONCRETE_SLAB, MAGENTA_CONCRETE_SLAB, PINK_CONCRETE_SLAB,
                TERRACOTTA_SLAB, TERRACOTTA_BRICK_SLAB,
                WHITE_TERRACOTTA_SLAB, WHITE_TERRACOTTA_BRICK_SLAB, LIGHT_GRAY_TERRACOTTA_SLAB, LIGHT_GRAY_TERRACOTTA_BRICK_SLAB, GRAY_TERRACOTTA_SLAB, GRAY_TERRACOTTA_BRICK_SLAB, BLACK_TERRACOTTA_SLAB, BLACK_TERRACOTTA_BRICK_SLAB,
                BROWN_TERRACOTTA_SLAB, BROWN_TERRACOTTA_BRICK_SLAB, RED_TERRACOTTA_SLAB, RED_TERRACOTTA_BRICK_SLAB, ORANGE_TERRACOTTA_SLAB, ORANGE_TERRACOTTA_BRICK_SLAB, YELLOW_TERRACOTTA_SLAB, YELLOW_TERRACOTTA_BRICK_SLAB,
                LIME_TERRACOTTA_SLAB, LIME_TERRACOTTA_BRICK_SLAB, GREEN_TERRACOTTA_SLAB, GREEN_TERRACOTTA_BRICK_SLAB, CYAN_TERRACOTTA_SLAB, CYAN_TERRACOTTA_BRICK_SLAB, LIGHT_BLUE_TERRACOTTA_SLAB, LIGHT_BLUE_TERRACOTTA_BRICK_SLAB,
                BLUE_TERRACOTTA_SLAB, BLUE_TERRACOTTA_BRICK_SLAB, PURPLE_TERRACOTTA_SLAB, PURPLE_TERRACOTTA_BRICK_SLAB, MAGENTA_TERRACOTTA_SLAB, MAGENTA_TERRACOTTA_BRICK_SLAB, PINK_TERRACOTTA_SLAB, PINK_TERRACOTTA_BRICK_SLAB,
                CHALK_SLAB, CHALK_BRICK_SLAB,
                WHITE_CHALK_SLAB, WHITE_CHALK_BRICK_SLAB, LIGHT_GRAY_CHALK_SLAB, LIGHT_GRAY_CHALK_BRICK_SLAB, GRAY_CHALK_SLAB, GRAY_CHALK_BRICK_SLAB, BLACK_CHALK_SLAB, BLACK_CHALK_BRICK_SLAB,
                BROWN_CHALK_SLAB, BROWN_CHALK_BRICK_SLAB, RED_CHALK_SLAB, RED_CHALK_BRICK_SLAB, ORANGE_CHALK_SLAB, ORANGE_CHALK_BRICK_SLAB, YELLOW_CHALK_SLAB, YELLOW_CHALK_BRICK_SLAB,
                LIME_CHALK_SLAB, LIME_CHALK_BRICK_SLAB, GREEN_CHALK_SLAB, GREEN_CHALK_BRICK_SLAB, CYAN_CHALK_SLAB, CYAN_CHALK_BRICK_SLAB, LIGHT_BLUE_CHALK_SLAB, LIGHT_BLUE_CHALK_BRICK_SLAB,
                BLUE_CHALK_SLAB, BLUE_CHALK_BRICK_SLAB, PURPLE_CHALK_SLAB, PURPLE_CHALK_BRICK_SLAB, MAGENTA_CHALK_SLAB, MAGENTA_CHALK_BRICK_SLAB, PINK_CHALK_SLAB, PINK_CHALK_BRICK_SLAB,
        };

        for (Block slab : slabs) {
            addDrop(slab, slabDrops(slab));
        }

        Block[] doors = {
                MAPLE_DOOR, POPLAR_DOOR, BEECH_DOOR, HICKORY_DOOR, WALNUT_DOOR, CHESTNUT_DOOR, CEDAR_DOOR, REDWOOD_DOOR, FIR_DOOR, HEMLOCK_DOOR,
                HOLLY_DOOR, PINE_DOOR, LARCH_DOOR, ASPEN_DOOR, KAPOK_DOOR, MAHOGANY_DOOR, EUCALYPTUS_DOOR, BAOBAB_DOOR, PALO_VERDE_DOOR, JOSHUA_DOOR,
                JUNIPER_DOOR, PALM_DOOR, EBONY_DOOR, TEAK_DOOR, ELM_DOOR, WILLOW_DOOR, CYPRESS_DOOR, SAKURA_DOOR, MAGNOLIA_DOOR, JACARANDA_DOOR
        };

        for (Block door : doors) {
            addDrop(door, doorDrops(door));
        }

        Block[] coalOres = {
                GRANITE_COAL_ORE, DIORITE_COAL_ORE, ANDESITE_COAL_ORE, TUFF_COAL_ORE, GNEISS_COAL_ORE, SHALE_COAL_ORE, LIMESTONE_COAL_ORE, MARBLE_COAL_ORE, GABBRO_COAL_ORE, PHYLLITE_COAL_ORE,
        };

        Block[] ironOres = {
                GRANITE_IRON_ORE, DIORITE_IRON_ORE, ANDESITE_IRON_ORE, TUFF_IRON_ORE, GNEISS_IRON_ORE, SHALE_IRON_ORE, LIMESTONE_IRON_ORE, MARBLE_IRON_ORE, GABBRO_IRON_ORE, PHYLLITE_IRON_ORE,
        };

        Block[] copperOres = {
                GRANITE_COPPER_ORE, DIORITE_COPPER_ORE, ANDESITE_COPPER_ORE, TUFF_COPPER_ORE, GNEISS_COPPER_ORE, SHALE_COPPER_ORE, LIMESTONE_COPPER_ORE, MARBLE_COPPER_ORE, GABBRO_COPPER_ORE, PHYLLITE_COPPER_ORE,
        };

        Block[] goldOres = {
                GRANITE_GOLD_ORE, DIORITE_GOLD_ORE, ANDESITE_GOLD_ORE, TUFF_GOLD_ORE, GNEISS_GOLD_ORE, SHALE_GOLD_ORE, LIMESTONE_GOLD_ORE, MARBLE_GOLD_ORE, GABBRO_GOLD_ORE, PHYLLITE_GOLD_ORE,
        };

        Block[] emeraldOres = {
                GRANITE_EMERALD_ORE, DIORITE_EMERALD_ORE, ANDESITE_EMERALD_ORE, TUFF_EMERALD_ORE, GNEISS_EMERALD_ORE, SHALE_EMERALD_ORE, LIMESTONE_EMERALD_ORE, MARBLE_EMERALD_ORE, GABBRO_EMERALD_ORE, PHYLLITE_EMERALD_ORE,
        };

        Block[] redstoneOres = {
                GRANITE_REDSTONE_ORE, DIORITE_REDSTONE_ORE, ANDESITE_REDSTONE_ORE, TUFF_REDSTONE_ORE, GNEISS_REDSTONE_ORE, SHALE_REDSTONE_ORE, LIMESTONE_REDSTONE_ORE, MARBLE_REDSTONE_ORE, GABBRO_REDSTONE_ORE, PHYLLITE_REDSTONE_ORE,
        };

        Block[] lapisOres = {
                GRANITE_LAPIS_ORE, DIORITE_LAPIS_ORE, ANDESITE_LAPIS_ORE, TUFF_LAPIS_ORE, GNEISS_LAPIS_ORE, SHALE_LAPIS_ORE, LIMESTONE_LAPIS_ORE, MARBLE_LAPIS_ORE, GABBRO_LAPIS_ORE, PHYLLITE_LAPIS_ORE,
        };

        Block[] diamondOres = {
                GRANITE_DIAMOND_ORE, DIORITE_DIAMOND_ORE, ANDESITE_DIAMOND_ORE, TUFF_DIAMOND_ORE, GNEISS_DIAMOND_ORE, SHALE_DIAMOND_ORE, LIMESTONE_DIAMOND_ORE, MARBLE_DIAMOND_ORE, GABBRO_DIAMOND_ORE, PHYLLITE_DIAMOND_ORE,
        };

        for (Block coalOre : coalOres) {
            addDrop(coalOre, oreDrops(coalOre, COAL));
        }

        for (Block ironOre : ironOres) {
            addDrop(ironOre, oreDrops(ironOre, RAW_IRON));
        }

        for (Block copperOre : copperOres) {
            addDrop(copperOre, copperOreDrops(copperOre));
        }

        for (Block goldOre : goldOres) {
            addDrop(goldOre, oreDrops(goldOre, RAW_GOLD));
        }

        for (Block emeraldOre : emeraldOres) {
            addDrop(emeraldOre, oreDrops(emeraldOre, EMERALD));
        }

        for (Block redstoneOre : redstoneOres) {
            addDrop(redstoneOre, redstoneOreDrops(redstoneOre));
        }

        for (Block lapisOre : lapisOres) {
            addDrop(lapisOre, lapisOreDrops(lapisOre));
        }

        for (Block diamondOre : diamondOres) {
            addDrop(diamondOre, oreDrops(diamondOre, DIAMOND));
        }

        float[] saplingChance = {
                0.05F, 0.0625F, 0.083333336F, 0.1F
        };

        addDrop(MAPLE_LEAVES, leavesDrops(MAPLE_LEAVES, MAPLE_SAPLING, saplingChance));
        addDrop(POPLAR_LEAVES, leavesDrops(POPLAR_LEAVES, POPLAR_SAPLING, saplingChance));
        addDrop(BEECH_LEAVES, leavesDrops(BEECH_LEAVES, BEECH_SAPLING, saplingChance));
        addDrop(HICKORY_LEAVES, leavesDrops(HICKORY_LEAVES, HICKORY_SAPLING, saplingChance));
        addDrop(WALNUT_LEAVES, leavesDrops(WALNUT_LEAVES, WALNUT_SAPLING, saplingChance));
        addDrop(CHESTNUT_LEAVES, leavesDrops(CHESTNUT_LEAVES, CHESTNUT_SAPLING, saplingChance));
        addDrop(CEDAR_LEAVES, leavesDrops(CEDAR_LEAVES, CEDAR_SAPLING, saplingChance));
        addDrop(REDWOOD_LEAVES, leavesDrops(REDWOOD_LEAVES, REDWOOD_SAPLING, saplingChance));
        addDrop(FIR_LEAVES, leavesDrops(FIR_LEAVES, FIR_SAPLING, saplingChance));
        addDrop(HEMLOCK_LEAVES, leavesDrops(HEMLOCK_LEAVES, HEMLOCK_SAPLING, saplingChance));
        addDrop(HOLLY_LEAVES, leavesDrops(HOLLY_LEAVES, HOLLY_SAPLING, saplingChance));
        addDrop(PINE_LEAVES, leavesDrops(PINE_LEAVES, PINE_SAPLING, saplingChance));
        addDrop(LARCH_LEAVES, leavesDrops(LARCH_LEAVES, LARCH_SAPLING, saplingChance));
        addDrop(ASPEN_LEAVES, leavesDrops(ASPEN_LEAVES, ASPEN_SAPLING, saplingChance));
        addDrop(KAPOK_LEAVES, leavesDrops(KAPOK_LEAVES, KAPOK_SAPLING, saplingChance));
        addDrop(MAHOGANY_LEAVES, leavesDrops(MAHOGANY_LEAVES, MAHOGANY_SAPLING, saplingChance));
        addDrop(EUCALYPTUS_LEAVES, leavesDrops(EUCALYPTUS_LEAVES, EUCALYPTUS_SAPLING, saplingChance));
        addDrop(BAOBAB_LEAVES, leavesDrops(BAOBAB_LEAVES, BAOBAB_SAPLING, saplingChance));
        addDrop(PALO_VERDE_LEAVES, leavesDrops(PALO_VERDE_LEAVES, PALO_VERDE_SAPLING, saplingChance));
        addDrop(JOSHUA_LEAVES, leavesDrops(JOSHUA_LEAVES, JOSHUA_SAPLING, saplingChance));
        addDrop(JUNIPER_LEAVES, leavesDrops(JUNIPER_LEAVES, JUNIPER_SAPLING, saplingChance));
        addDrop(PALM_LEAVES, leavesDrops(PALM_LEAVES, PALM_SAPLING, saplingChance));
        addDrop(EBONY_LEAVES, leavesDrops(EBONY_LEAVES, EBONY_SAPLING, saplingChance));
        addDrop(TEAK_LEAVES, leavesDrops(TEAK_LEAVES, TEAK_SAPLING, saplingChance));
        addDrop(ELM_LEAVES, leavesDrops(ELM_LEAVES, ELM_SAPLING, saplingChance));
        addDrop(WILLOW_LEAVES, leavesDrops(WILLOW_LEAVES, WILLOW_SAPLING, saplingChance));
        addDrop(CYPRESS_LEAVES, leavesDrops(CYPRESS_LEAVES, CYPRESS_SAPLING, saplingChance));
        addDrop(SAKURA_LEAVES, leavesDrops(SAKURA_LEAVES, SAKURA_SAPLING, saplingChance));
        addDrop(MAGNOLIA_LEAVES, leavesDrops(MAGNOLIA_LEAVES, MAGNOLIA_SAPLING, saplingChance));
        addDrop(FLOWERING_MAGNOLIA_LEAVES, leavesDrops(FLOWERING_MAGNOLIA_LEAVES, FLOWERING_MAGNOLIA_SAPLING, saplingChance));
        addDrop(JACARANDA_LEAVES, leavesDrops(JACARANDA_LEAVES, JACARANDA_SAPLING, saplingChance));

        addDrop(SHORT_PRAIRIE_GRASS, (block) -> shortPlantDrops(SHORT_PRAIRIE_GRASS));
        addDrop(TALL_PRAIRIE_GRASS, (block -> tallPlantDrops(block, SHORT_PRAIRIE_GRASS)));
        addDrop(CATTAIL, this::dropsWithShears);
        addDrop(PURPLE_PETALS, segmentedDrops(PURPLE_PETALS));
        addDrop(HANGING_MOSS, this::dropsWithSilkTouchOrShears);
    }
}