package me.withers_overhaul.datagen.fabric;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

import static me.withers_overhaul.registry.block.ColoredBlocks.*;
import static me.withers_overhaul.registry.block.NaturalBlocks.*;
import static me.withers_overhaul.registry.block.StoneBlocks.*;
import static me.withers_overhaul.registry.block.WoodBlocks.*;
import static me.withers_overhaul.tag.OverhaulBlockTags.*;
import static net.minecraft.registry.tag.BlockTags.*;

public class BlockTagGen extends FabricTagProvider.BlockTagProvider {
    public BlockTagGen(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
        super(dataOutput, completableFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {

        getOrCreateTagBuilder(PICKAXE_MINEABLE)
                .add(STONE_WALL, SMOOTH_STONE_STAIRS, SMOOTH_STONE_WALL, STONE_BRICK_PILLAR)
                .add(POLISHED_GRANITE_WALL, GRANITE_BRICKS, CRACKED_GRANITE_BRICKS, GRANITE_BRICK_STAIRS, GRANITE_BRICK_SLAB, GRANITE_BRICK_WALL, MOSSY_GRANITE_BRICKS, MOSSY_GRANITE_BRICK_STAIRS, MOSSY_GRANITE_BRICK_SLAB, MOSSY_GRANITE_BRICK_WALL, GRANITE_BRICK_PILLAR, CHISELED_GRANITE_BRICKS, POLISHED_GRANITE_BUTTON, POLISHED_GRANITE_PRESSURE_PLATE)
                .add(POLISHED_DIORITE_WALL, DIORITE_BRICKS, CRACKED_DIORITE_BRICKS, DIORITE_BRICK_STAIRS, DIORITE_BRICK_SLAB, DIORITE_BRICK_WALL, MOSSY_DIORITE_BRICKS, MOSSY_DIORITE_BRICK_STAIRS, MOSSY_DIORITE_BRICK_SLAB, MOSSY_DIORITE_BRICK_WALL, DIORITE_BRICK_PILLAR, CHISELED_DIORITE_BRICKS, POLISHED_DIORITE_BUTTON, POLISHED_DIORITE_PRESSURE_PLATE)
                .add(POLISHED_ANDESITE_WALL, ANDESITE_BRICKS, CRACKED_ANDESITE_BRICKS, ANDESITE_BRICK_STAIRS, ANDESITE_BRICK_SLAB, ANDESITE_BRICK_WALL, MOSSY_ANDESITE_BRICKS, MOSSY_ANDESITE_BRICK_STAIRS, MOSSY_ANDESITE_BRICK_SLAB, MOSSY_ANDESITE_BRICK_WALL, ANDESITE_BRICK_PILLAR, CHISELED_ANDESITE_BRICKS, POLISHED_ANDESITE_BUTTON, POLISHED_ANDESITE_PRESSURE_PLATE)
                .add(GNEISS, GNEISS_STAIRS, GNEISS_SLAB, GNEISS_WALL, POLISHED_GNEISS, POLISHED_GNEISS_STAIRS, POLISHED_GNEISS_SLAB, POLISHED_GNEISS_WALL, GNEISS_BRICKS, CRACKED_GNEISS_BRICKS, GNEISS_BRICK_STAIRS, GNEISS_BRICK_SLAB, GNEISS_BRICK_WALL, MOSSY_GNEISS_BRICKS, MOSSY_GNEISS_BRICK_STAIRS, MOSSY_GNEISS_BRICK_SLAB, MOSSY_GNEISS_BRICK_WALL, GNEISS_BRICK_PILLAR, CHISELED_GNEISS_BRICKS, POLISHED_GNEISS_BUTTON, POLISHED_GNEISS_PRESSURE_PLATE)
                .add(SHALE, SHALE_STAIRS, SHALE_SLAB, SHALE_WALL, POLISHED_SHALE, POLISHED_SHALE_STAIRS, POLISHED_SHALE_SLAB, POLISHED_SHALE_WALL, SHALE_BRICKS, CRACKED_SHALE_BRICKS, SHALE_BRICK_STAIRS, SHALE_BRICK_SLAB, SHALE_BRICK_WALL, MOSSY_SHALE_BRICKS, MOSSY_SHALE_BRICK_STAIRS, MOSSY_SHALE_BRICK_SLAB, MOSSY_SHALE_BRICK_WALL, SHALE_BRICK_PILLAR, CHISELED_SHALE_BRICKS, POLISHED_SHALE_BUTTON, POLISHED_SHALE_PRESSURE_PLATE)
                .add(LIMESTONE, LIMESTONE_STAIRS, LIMESTONE_SLAB, LIMESTONE_WALL, POLISHED_LIMESTONE, POLISHED_LIMESTONE_STAIRS, POLISHED_LIMESTONE_SLAB, POLISHED_LIMESTONE_WALL, LIMESTONE_BRICKS, CRACKED_LIMESTONE_BRICKS, LIMESTONE_BRICK_STAIRS, LIMESTONE_BRICK_SLAB, LIMESTONE_BRICK_WALL, MOSSY_LIMESTONE_BRICKS, MOSSY_LIMESTONE_BRICK_STAIRS, MOSSY_LIMESTONE_BRICK_SLAB, MOSSY_LIMESTONE_BRICK_WALL, LIMESTONE_BRICK_PILLAR, CHISELED_LIMESTONE_BRICKS, POLISHED_LIMESTONE_BUTTON, POLISHED_LIMESTONE_PRESSURE_PLATE)
                .add(MARBLE, MARBLE_STAIRS, MARBLE_SLAB, MARBLE_WALL, POLISHED_MARBLE, POLISHED_MARBLE_STAIRS, POLISHED_MARBLE_SLAB, POLISHED_MARBLE_WALL, MARBLE_BRICKS, CRACKED_MARBLE_BRICKS, MARBLE_BRICK_STAIRS, MARBLE_BRICK_SLAB, MARBLE_BRICK_WALL, MOSSY_MARBLE_BRICKS, MOSSY_MARBLE_BRICK_STAIRS, MOSSY_MARBLE_BRICK_SLAB, MOSSY_MARBLE_BRICK_WALL, MARBLE_BRICK_PILLAR, CHISELED_MARBLE_BRICKS, POLISHED_MARBLE_BUTTON, POLISHED_MARBLE_PRESSURE_PLATE)
                .add(GABBRO, GABBRO_STAIRS, GABBRO_SLAB, GABBRO_WALL, POLISHED_GABBRO, POLISHED_GABBRO_STAIRS, POLISHED_GABBRO_SLAB, POLISHED_GABBRO_WALL, GABBRO_BRICKS, CRACKED_GABBRO_BRICKS, GABBRO_BRICK_STAIRS, GABBRO_BRICK_SLAB, GABBRO_BRICK_WALL, MOSSY_GABBRO_BRICKS, MOSSY_GABBRO_BRICK_STAIRS, MOSSY_GABBRO_BRICK_SLAB, MOSSY_GABBRO_BRICK_WALL, GABBRO_BRICK_PILLAR, CHISELED_GABBRO_BRICKS, POLISHED_GABBRO_BUTTON, POLISHED_GABBRO_PRESSURE_PLATE)
                .add(PHYLLITE, PHYLLITE_STAIRS, PHYLLITE_SLAB, PHYLLITE_WALL, POLISHED_PHYLLITE, POLISHED_PHYLLITE_STAIRS, POLISHED_PHYLLITE_SLAB, POLISHED_PHYLLITE_WALL, PHYLLITE_BRICKS, CRACKED_PHYLLITE_BRICKS, PHYLLITE_BRICK_STAIRS, PHYLLITE_BRICK_SLAB, PHYLLITE_BRICK_WALL, MOSSY_PHYLLITE_BRICKS, MOSSY_PHYLLITE_BRICK_STAIRS, MOSSY_PHYLLITE_BRICK_SLAB, MOSSY_PHYLLITE_BRICK_WALL, PHYLLITE_BRICK_PILLAR, CHISELED_PHYLLITE_BRICKS, POLISHED_PHYLLITE_BUTTON, POLISHED_PHYLLITE_PRESSURE_PLATE)
                .add(CRACKED_TUFF_BRICKS)
                .add(CALCITE_STAIRS, CALCITE_SLAB, CALCITE_WALL, POLISHED_CALCITE, POLISHED_CALCITE_STAIRS, POLISHED_CALCITE_SLAB, POLISHED_CALCITE_WALL, CALCITE_BRICKS, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_STAIRS, CALCITE_BRICK_SLAB, CALCITE_BRICK_WALL, CHISELED_CALCITE)
                .add(DRIPSTONE_STAIRS, DRIPSTONE_SLAB, DRIPSTONE_WALL, POLISHED_DRIPSTONE, POLISHED_DRIPSTONE_STAIRS, POLISHED_DRIPSTONE_SLAB, POLISHED_DRIPSTONE_WALL, DRIPSTONE_BRICKS, CRACKED_DRIPSTONE_BRICKS, DRIPSTONE_BRICK_STAIRS, DRIPSTONE_BRICK_SLAB, DRIPSTONE_BRICK_WALL, CHISELED_DRIPSTONE)
                .add(CRACKED_BRICKS, CRACKED_MUD_BRICKS, CHISELED_MUD_BRICKS)
                .add(CUT_SANDSTONE_STAIRS, CUT_SANDSTONE_WALL, SMOOTH_SANDSTONE_WALL, ROUGH_SANDSTONE, ROUGH_SANDSTONE_STAIRS, ROUGH_SANDSTONE_SLAB, ROUGH_SANDSTONE_WALL)
                .add(CUT_RED_SANDSTONE_STAIRS, CUT_RED_SANDSTONE_WALL, SMOOTH_RED_SANDSTONE_WALL, ROUGH_RED_SANDSTONE, ROUGH_RED_SANDSTONE_STAIRS, ROUGH_RED_SANDSTONE_SLAB, ROUGH_RED_SANDSTONE_WALL)
                .add(CRACKED_PRISMARINE_BRICKS, PRISMARINE_BRICK_WALL, DARK_PRISMARINE_WALL, CHISELED_PRISMARINE_BRICKS)
                .add(CRACKED_RED_NETHER_BRICKS, RED_NETHER_BRICK_FENCE, CHISELED_RED_NETHER_BRICKS, BLUE_NETHER_BRICKS, CRACKED_BLUE_NETHER_BRICKS, BLUE_NETHER_BRICK_STAIRS, BLUE_NETHER_BRICK_SLAB, BLUE_NETHER_BRICK_WALL, BLUE_NETHER_BRICK_FENCE, CHISELED_BLUE_NETHER_BRICKS)
                .add(QUARTZ_WALL, CRACKED_QUARTZ_BRICKS, QUARTZ_BRICK_STAIRS, QUARTZ_BRICK_SLAB, QUARTZ_BRICK_WALL, SMOOTH_QUARTZ_WALL)
                .add(AMETHYST_STAIRS, AMETHYST_SLAB, AMETHYST_WALL, AMETHYST_BRICKS, CRACKED_AMETHYST_BRICKS, AMETHYST_BRICK_STAIRS, AMETHYST_BRICK_SLAB, AMETHYST_BRICK_WALL, AMETHYST_TILES, CRACKED_AMETHYST_TILES, AMETHYST_TILE_STAIRS, AMETHYST_TILE_SLAB, AMETHYST_TILE_WALL, CHISELED_AMETHYST)
                .add(DOLOMITE, DOLOMITE_STAIRS, DOLOMITE_SLAB, DOLOMITE_WALL, DOLOMITE_BRICKS, CRACKED_DOLOMITE_BRICKS, DOLOMITE_BRICK_STAIRS, DOLOMITE_BRICK_SLAB, DOLOMITE_BRICK_WALL, DOLOMITE_TILES, CRACKED_DOLOMITE_TILES, DOLOMITE_TILE_STAIRS, DOLOMITE_TILE_SLAB, DOLOMITE_TILE_WALL, CHISELED_DOLOMITE)
                .add(GYPSUM, GYPSUM_STAIRS, GYPSUM_SLAB, GYPSUM_WALL, GYPSUM_BRICKS, CRACKED_GYPSUM_BRICKS, GYPSUM_BRICK_STAIRS, GYPSUM_BRICK_SLAB, GYPSUM_BRICK_WALL, GYPSUM_TILES, CRACKED_GYPSUM_TILES, GYPSUM_TILE_STAIRS, GYPSUM_TILE_SLAB, GYPSUM_TILE_WALL, CHISELED_GYPSUM)
                .addOptionalTag(COAL_ORES).addOptionalTag(IRON_ORES).addOptionalTag(COPPER_ORES).addOptionalTag(GOLD_ORES).addOptionalTag(EMERALD_ORES).addOptionalTag(REDSTONE_ORES).addOptionalTag(LAPIS_ORES).addOptionalTag(DIAMOND_ORES)
                .add(WHITE_CONCRETE_STAIRS, WHITE_CONCRETE_SLAB, WHITE_CONCRETE_WALL, LIGHT_GRAY_CONCRETE_STAIRS, LIGHT_GRAY_CONCRETE_SLAB, LIGHT_GRAY_CONCRETE_WALL, GRAY_CONCRETE_STAIRS, GRAY_CONCRETE_SLAB, GRAY_CONCRETE_WALL, BLACK_CONCRETE_STAIRS, BLACK_CONCRETE_SLAB, BLACK_CONCRETE_WALL)
                .add(BROWN_CONCRETE_STAIRS, BROWN_CONCRETE_SLAB, BROWN_CONCRETE_WALL, RED_CONCRETE_STAIRS, RED_CONCRETE_SLAB, RED_CONCRETE_WALL, ORANGE_CONCRETE_STAIRS, ORANGE_CONCRETE_SLAB, ORANGE_CONCRETE_WALL, YELLOW_CONCRETE_STAIRS, YELLOW_CONCRETE_SLAB, YELLOW_CONCRETE_WALL)
                .add(LIME_CONCRETE_STAIRS, LIME_CONCRETE_SLAB, LIME_CONCRETE_WALL, GREEN_CONCRETE_STAIRS, GREEN_CONCRETE_SLAB, GREEN_CONCRETE_WALL, CYAN_CONCRETE_STAIRS, CYAN_CONCRETE_SLAB, CYAN_CONCRETE_WALL, LIGHT_BLUE_CONCRETE_STAIRS, LIGHT_BLUE_CONCRETE_SLAB, LIGHT_BLUE_CONCRETE_WALL)
                .add(BLUE_CONCRETE_STAIRS, BLUE_CONCRETE_SLAB, BLUE_CONCRETE_WALL, PURPLE_CONCRETE_STAIRS, PURPLE_CONCRETE_SLAB, PURPLE_CONCRETE_WALL, MAGENTA_CONCRETE_STAIRS, MAGENTA_CONCRETE_SLAB, MAGENTA_CONCRETE_WALL, PINK_CONCRETE_STAIRS, PINK_CONCRETE_SLAB, PINK_CONCRETE_WALL)
                .add(TERRACOTTA_STAIRS, TERRACOTTA_SLAB, TERRACOTTA_WALL, WHITE_TERRACOTTA_STAIRS, WHITE_TERRACOTTA_SLAB, WHITE_TERRACOTTA_WALL, LIGHT_GRAY_TERRACOTTA_STAIRS, LIGHT_GRAY_TERRACOTTA_SLAB, LIGHT_GRAY_TERRACOTTA_WALL, GRAY_TERRACOTTA_STAIRS, GRAY_TERRACOTTA_SLAB, GRAY_TERRACOTTA_WALL, BLACK_TERRACOTTA_STAIRS, BLACK_TERRACOTTA_SLAB, BLACK_TERRACOTTA_WALL)
                .add(BROWN_TERRACOTTA_STAIRS, BROWN_TERRACOTTA_SLAB, BROWN_TERRACOTTA_WALL, RED_TERRACOTTA_STAIRS, RED_TERRACOTTA_SLAB, RED_TERRACOTTA_WALL, ORANGE_TERRACOTTA_STAIRS, ORANGE_TERRACOTTA_SLAB, ORANGE_TERRACOTTA_WALL, YELLOW_TERRACOTTA_STAIRS, YELLOW_TERRACOTTA_SLAB, YELLOW_TERRACOTTA_WALL)
                .add(LIME_TERRACOTTA_STAIRS, LIME_TERRACOTTA_SLAB, LIME_TERRACOTTA_WALL, GREEN_TERRACOTTA_STAIRS, GREEN_TERRACOTTA_SLAB, GREEN_TERRACOTTA_WALL, CYAN_TERRACOTTA_STAIRS, CYAN_TERRACOTTA_SLAB, CYAN_TERRACOTTA_WALL, LIGHT_BLUE_TERRACOTTA_STAIRS, LIGHT_BLUE_TERRACOTTA_SLAB, LIGHT_BLUE_TERRACOTTA_WALL)
                .add(BLUE_TERRACOTTA_STAIRS, BLUE_TERRACOTTA_SLAB, BLUE_TERRACOTTA_WALL, PURPLE_TERRACOTTA_STAIRS, PURPLE_TERRACOTTA_SLAB, PURPLE_TERRACOTTA_WALL, MAGENTA_TERRACOTTA_STAIRS, MAGENTA_TERRACOTTA_SLAB, MAGENTA_TERRACOTTA_WALL, PINK_TERRACOTTA_STAIRS, PINK_TERRACOTTA_SLAB, PINK_TERRACOTTA_WALL)
                .add(TERRACOTTA_BRICKS, TERRACOTTA_BRICK_STAIRS, TERRACOTTA_BRICK_SLAB, TERRACOTTA_BRICK_WALL, WHITE_TERRACOTTA_BRICKS, WHITE_TERRACOTTA_BRICK_STAIRS, WHITE_TERRACOTTA_BRICK_SLAB, WHITE_TERRACOTTA_BRICK_WALL, LIGHT_GRAY_TERRACOTTA_BRICKS, LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS, LIGHT_GRAY_TERRACOTTA_BRICK_SLAB, LIGHT_GRAY_TERRACOTTA_BRICK_WALL, GRAY_TERRACOTTA_BRICKS, GRAY_TERRACOTTA_BRICK_STAIRS, GRAY_TERRACOTTA_BRICK_SLAB, GRAY_TERRACOTTA_BRICK_WALL, BLACK_TERRACOTTA_BRICKS, BLACK_TERRACOTTA_BRICK_STAIRS, BLACK_TERRACOTTA_BRICK_SLAB, BLACK_TERRACOTTA_BRICK_WALL)
                .add(BROWN_TERRACOTTA_BRICKS, BROWN_TERRACOTTA_BRICK_STAIRS, BROWN_TERRACOTTA_BRICK_SLAB, BROWN_TERRACOTTA_BRICK_WALL, RED_TERRACOTTA_BRICKS, RED_TERRACOTTA_BRICK_STAIRS, RED_TERRACOTTA_BRICK_SLAB, RED_TERRACOTTA_BRICK_WALL, ORANGE_TERRACOTTA_BRICKS, ORANGE_TERRACOTTA_BRICK_STAIRS, ORANGE_TERRACOTTA_BRICK_SLAB, ORANGE_TERRACOTTA_BRICK_WALL, YELLOW_TERRACOTTA_BRICKS, YELLOW_TERRACOTTA_BRICK_STAIRS, YELLOW_TERRACOTTA_BRICK_SLAB, YELLOW_TERRACOTTA_BRICK_WALL)
                .add(LIME_TERRACOTTA_BRICKS, LIME_TERRACOTTA_BRICK_STAIRS, LIME_TERRACOTTA_BRICK_SLAB, LIME_TERRACOTTA_BRICK_WALL, GREEN_TERRACOTTA_BRICKS, GREEN_TERRACOTTA_BRICK_STAIRS, GREEN_TERRACOTTA_BRICK_SLAB, GREEN_TERRACOTTA_BRICK_WALL, CYAN_TERRACOTTA_BRICKS, CYAN_TERRACOTTA_BRICK_STAIRS, CYAN_TERRACOTTA_BRICK_SLAB, CYAN_TERRACOTTA_BRICK_WALL, LIGHT_BLUE_TERRACOTTA_BRICKS, LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS, LIGHT_BLUE_TERRACOTTA_BRICK_SLAB, LIGHT_BLUE_TERRACOTTA_BRICK_WALL)
                .add(BLUE_TERRACOTTA_BRICKS, BLUE_TERRACOTTA_BRICK_STAIRS, BLUE_TERRACOTTA_BRICK_SLAB, BLUE_TERRACOTTA_BRICK_WALL, PURPLE_TERRACOTTA_BRICKS, PURPLE_TERRACOTTA_BRICK_STAIRS, PURPLE_TERRACOTTA_BRICK_SLAB, PURPLE_TERRACOTTA_BRICK_WALL, MAGENTA_TERRACOTTA_BRICKS, MAGENTA_TERRACOTTA_BRICK_STAIRS, MAGENTA_TERRACOTTA_BRICK_SLAB, MAGENTA_TERRACOTTA_BRICK_WALL, PINK_TERRACOTTA_BRICKS, PINK_TERRACOTTA_BRICK_STAIRS, PINK_TERRACOTTA_BRICK_SLAB, PINK_TERRACOTTA_BRICK_WALL)
                .add(CHALK, CHALK_STAIRS, CHALK_SLAB, CHALK_WALL, WHITE_CHALK, WHITE_CHALK_STAIRS, WHITE_CHALK_SLAB, WHITE_CHALK_WALL, LIGHT_GRAY_CHALK, LIGHT_GRAY_CHALK_STAIRS, LIGHT_GRAY_CHALK_SLAB, LIGHT_GRAY_CHALK_WALL, GRAY_CHALK, GRAY_CHALK_STAIRS, GRAY_CHALK_SLAB, GRAY_CHALK_WALL, BLACK_CHALK, BLACK_CHALK_STAIRS, BLACK_CHALK_SLAB, BLACK_CHALK_WALL)
                .add(BROWN_CHALK, BROWN_CHALK_STAIRS, BROWN_CHALK_SLAB, BROWN_CHALK_WALL, RED_CHALK, RED_CHALK_STAIRS, RED_CHALK_SLAB, RED_CHALK_WALL, ORANGE_CHALK, ORANGE_CHALK_STAIRS, ORANGE_CHALK_SLAB, ORANGE_CHALK_WALL, YELLOW_CHALK, YELLOW_CHALK_STAIRS, YELLOW_CHALK_SLAB, YELLOW_CHALK_WALL)
                .add(LIME_CHALK, LIME_CHALK_STAIRS, LIME_CHALK_SLAB, LIME_CHALK_WALL, GREEN_CHALK, GREEN_CHALK_STAIRS, GREEN_CHALK_SLAB, GREEN_CHALK_WALL, CYAN_CHALK, CYAN_CHALK_STAIRS, CYAN_CHALK_SLAB, CYAN_CHALK_WALL, LIGHT_BLUE_CHALK, LIGHT_BLUE_CHALK_STAIRS, LIGHT_BLUE_CHALK_SLAB, LIGHT_BLUE_CHALK_WALL)
                .add(BLUE_CHALK, BLUE_CHALK_STAIRS, BLUE_CHALK_SLAB, BLUE_CHALK_WALL, PURPLE_CHALK, PURPLE_CHALK_STAIRS, PURPLE_CHALK_SLAB, PURPLE_CHALK_WALL, MAGENTA_CHALK, MAGENTA_CHALK_STAIRS, MAGENTA_CHALK_SLAB, MAGENTA_CHALK_WALL, PINK_CHALK, PINK_CHALK_STAIRS, PINK_CHALK_SLAB, PINK_CHALK_WALL)
                .add(CHALK_BRICKS, CHALK_BRICK_STAIRS, CHALK_BRICK_SLAB, CHALK_BRICK_WALL, WHITE_CHALK_BRICKS, WHITE_CHALK_BRICK_STAIRS, WHITE_CHALK_BRICK_SLAB, WHITE_CHALK_BRICK_WALL, LIGHT_GRAY_CHALK_BRICKS, LIGHT_GRAY_CHALK_BRICK_STAIRS, LIGHT_GRAY_CHALK_BRICK_SLAB, LIGHT_GRAY_CHALK_BRICK_WALL, GRAY_CHALK_BRICKS, GRAY_CHALK_BRICK_STAIRS, GRAY_CHALK_BRICK_SLAB, GRAY_CHALK_BRICK_WALL, BLACK_CHALK_BRICKS, BLACK_CHALK_BRICK_STAIRS, BLACK_CHALK_BRICK_SLAB, BLACK_CHALK_BRICK_WALL)
                .add(BROWN_CHALK_BRICKS, BROWN_CHALK_BRICK_STAIRS, BROWN_CHALK_BRICK_SLAB, BROWN_CHALK_BRICK_WALL, RED_CHALK_BRICKS, RED_CHALK_BRICK_STAIRS, RED_CHALK_BRICK_SLAB, RED_CHALK_BRICK_WALL, ORANGE_CHALK_BRICKS, ORANGE_CHALK_BRICK_STAIRS, ORANGE_CHALK_BRICK_SLAB, ORANGE_CHALK_BRICK_WALL, YELLOW_CHALK_BRICKS, YELLOW_CHALK_BRICK_STAIRS, YELLOW_CHALK_BRICK_SLAB, YELLOW_CHALK_BRICK_WALL)
                .add(LIME_CHALK_BRICKS, LIME_CHALK_BRICK_STAIRS, LIME_CHALK_BRICK_SLAB, LIME_CHALK_BRICK_WALL, GREEN_CHALK_BRICKS, GREEN_CHALK_BRICK_STAIRS, GREEN_CHALK_BRICK_SLAB, GREEN_CHALK_BRICK_WALL, CYAN_CHALK_BRICKS, CYAN_CHALK_BRICK_STAIRS, CYAN_CHALK_BRICK_SLAB, CYAN_CHALK_BRICK_WALL, LIGHT_BLUE_CHALK_BRICKS, LIGHT_BLUE_CHALK_BRICK_STAIRS, LIGHT_BLUE_CHALK_BRICK_SLAB, LIGHT_BLUE_CHALK_BRICK_WALL)
                .add(BLUE_CHALK_BRICKS, BLUE_CHALK_BRICK_STAIRS, BLUE_CHALK_BRICK_SLAB, BLUE_CHALK_BRICK_WALL, PURPLE_CHALK_BRICKS, PURPLE_CHALK_BRICK_STAIRS, PURPLE_CHALK_BRICK_SLAB, PURPLE_CHALK_BRICK_WALL, MAGENTA_CHALK_BRICKS, MAGENTA_CHALK_BRICK_STAIRS, MAGENTA_CHALK_BRICK_SLAB, MAGENTA_CHALK_BRICK_WALL, PINK_CHALK_BRICKS, PINK_CHALK_BRICK_STAIRS, PINK_CHALK_BRICK_SLAB, PINK_CHALK_BRICK_WALL)
                .add(FROSTED_SANDSTONE, FROSTED_SANDSTONE_STAIRS, FROSTED_SANDSTONE_SLAB, FROSTED_SANDSTONE_WALL, CHISELED_FROSTED_SANDSTONE, CUT_FROSTED_SANDSTONE, CUT_FROSTED_SANDSTONE_STAIRS, CUT_FROSTED_SANDSTONE_SLAB, CUT_FROSTED_SANDSTONE_WALL, SMOOTH_FROSTED_SANDSTONE, SMOOTH_FROSTED_SANDSTONE_STAIRS, SMOOTH_FROSTED_SANDSTONE_SLAB, SMOOTH_FROSTED_SANDSTONE_WALL, ROUGH_FROSTED_SANDSTONE, ROUGH_FROSTED_SANDSTONE_STAIRS, ROUGH_FROSTED_SANDSTONE_SLAB, ROUGH_FROSTED_SANDSTONE_WALL)
                .add(CHARRED_SANDSTONE, CHARRED_SANDSTONE_STAIRS, CHARRED_SANDSTONE_SLAB, CHARRED_SANDSTONE_WALL, CHISELED_CHARRED_SANDSTONE, CUT_CHARRED_SANDSTONE, CUT_CHARRED_SANDSTONE_STAIRS, CUT_CHARRED_SANDSTONE_SLAB, CUT_CHARRED_SANDSTONE_WALL, SMOOTH_CHARRED_SANDSTONE, SMOOTH_CHARRED_SANDSTONE_STAIRS, SMOOTH_CHARRED_SANDSTONE_SLAB, SMOOTH_CHARRED_SANDSTONE_WALL, ROUGH_CHARRED_SANDSTONE, ROUGH_CHARRED_SANDSTONE_STAIRS, ROUGH_CHARRED_SANDSTONE_SLAB, ROUGH_CHARRED_SANDSTONE_WALL);

        getOrCreateTagBuilder(AXE_MINEABLE)
                .add(GOURD, CARVED_GOURD);

        getOrCreateTagBuilder(SHOVEL_MINEABLE)
                .add(FROSTED_SAND, CHARRED_SAND);

        getOrCreateTagBuilder(HOE_MINEABLE)
                .addOptionalTag(LEAVES)
                .add(PEAT_BLOCK, PEAT, PURPLE_PETALS);

        getOrCreateTagBuilder(SWORD_EFFICIENT)
                .add(SHORT_PRAIRIE_GRASS, TALL_PRAIRIE_GRASS, GOURD, CARVED_GOURD, LAVENDER, PURPLE_PETALS);

        getOrCreateTagBuilder(BASE_STONE_OVERWORLD)
                .add(GNEISS, SHALE, LIMESTONE, MARBLE, GABBRO, PHYLLITE);

        getOrCreateTagBuilder(BEE_ATTRACTIVE)
                .add(LAVENDER, PURPLE_PETALS);

        getOrCreateTagBuilder(CEILING_HANGING_SIGNS)
                .add(MAPLE_HANGING_SIGN, POPLAR_HANGING_SIGN, BEECH_HANGING_SIGN, HICKORY_HANGING_SIGN, WALNUT_HANGING_SIGN, CHESTNUT_HANGING_SIGN, CEDAR_HANGING_SIGN, REDWOOD_HANGING_SIGN, FIR_HANGING_SIGN, HEMLOCK_HANGING_SIGN)
                .add(HOLLY_HANGING_SIGN, PINE_HANGING_SIGN, LARCH_HANGING_SIGN, ASPEN_HANGING_SIGN, KAPOK_HANGING_SIGN, MAHOGANY_HANGING_SIGN, EUCALYPTUS_HANGING_SIGN, BAOBAB_HANGING_SIGN, PALO_VERDE_HANGING_SIGN, JOSHUA_HANGING_SIGN)
                .add(JUNIPER_HANGING_SIGN, PALM_HANGING_SIGN, EBONY_HANGING_SIGN, TEAK_HANGING_SIGN, ELM_HANGING_SIGN, WILLOW_HANGING_SIGN, CYPRESS_HANGING_SIGN, SAKURA_HANGING_SIGN, MAGNOLIA_HANGING_SIGN, JACARANDA_HANGING_SIGN);

        getOrCreateTagBuilder(COAL_ORES)
                .add(GRANITE_COAL_ORE, DIORITE_COAL_ORE, ANDESITE_COAL_ORE, TUFF_COAL_ORE, GNEISS_COAL_ORE, SHALE_COAL_ORE, LIMESTONE_COAL_ORE, MARBLE_COAL_ORE, GABBRO_COAL_ORE, PHYLLITE_COAL_ORE);

        getOrCreateTagBuilder(COPPER_ORES)
                .add(GRANITE_COPPER_ORE, DIORITE_COPPER_ORE, ANDESITE_COPPER_ORE, TUFF_COPPER_ORE, GNEISS_COPPER_ORE, SHALE_COPPER_ORE, LIMESTONE_COPPER_ORE, MARBLE_COPPER_ORE, GABBRO_COPPER_ORE, PHYLLITE_COPPER_ORE);

        getOrCreateTagBuilder(CRYSTAL_SOUND_BLOCKS)
                .add(AMETHYST_STAIRS, AMETHYST_SLAB, AMETHYST_WALL, AMETHYST_BRICKS, CRACKED_AMETHYST_BRICKS, AMETHYST_BRICK_STAIRS, AMETHYST_BRICK_SLAB, AMETHYST_BRICK_WALL, AMETHYST_TILES, CRACKED_AMETHYST_TILES, AMETHYST_TILE_STAIRS, AMETHYST_TILE_SLAB, AMETHYST_TILE_WALL, CHISELED_AMETHYST)
                .add(DOLOMITE, DOLOMITE_STAIRS, DOLOMITE_SLAB, DOLOMITE_WALL, DOLOMITE_BRICKS, CRACKED_DOLOMITE_BRICKS, DOLOMITE_BRICK_STAIRS, DOLOMITE_BRICK_SLAB, DOLOMITE_BRICK_WALL, DOLOMITE_TILES, CRACKED_DOLOMITE_TILES, DOLOMITE_TILE_STAIRS, DOLOMITE_TILE_SLAB, DOLOMITE_TILE_WALL, CHISELED_DOLOMITE)
                .add(GYPSUM, GYPSUM_STAIRS, GYPSUM_SLAB, GYPSUM_WALL, GYPSUM_BRICKS, CRACKED_GYPSUM_BRICKS, GYPSUM_BRICK_STAIRS, GYPSUM_BRICK_SLAB, GYPSUM_BRICK_WALL, GYPSUM_TILES, CRACKED_GYPSUM_TILES, GYPSUM_TILE_STAIRS, GYPSUM_TILE_SLAB, GYPSUM_TILE_WALL, CHISELED_GYPSUM);

        getOrCreateTagBuilder(DIAMOND_ORES)
                .add(GRANITE_DIAMOND_ORE, DIORITE_DIAMOND_ORE, ANDESITE_DIAMOND_ORE, TUFF_DIAMOND_ORE, GNEISS_DIAMOND_ORE, SHALE_DIAMOND_ORE, LIMESTONE_DIAMOND_ORE, MARBLE_DIAMOND_ORE, GABBRO_DIAMOND_ORE, PHYLLITE_DIAMOND_ORE);

        getOrCreateTagBuilder(DIRT)
                .add(PEAT_BLOCK);

        getOrCreateTagBuilder(EMERALD_ORES)
                .add(GRANITE_EMERALD_ORE, DIORITE_EMERALD_ORE, ANDESITE_EMERALD_ORE, TUFF_EMERALD_ORE, GNEISS_EMERALD_ORE, SHALE_EMERALD_ORE, LIMESTONE_EMERALD_ORE, MARBLE_EMERALD_ORE, GABBRO_EMERALD_ORE, PHYLLITE_EMERALD_ORE);

        getOrCreateTagBuilder(FENCE_GATES)
                .add(MAPLE_FENCE_GATE, POPLAR_FENCE_GATE, BEECH_FENCE_GATE, HICKORY_FENCE_GATE, WALNUT_FENCE_GATE, CHESTNUT_FENCE_GATE, CEDAR_FENCE_GATE, REDWOOD_FENCE_GATE, FIR_FENCE_GATE, HEMLOCK_FENCE_GATE)
                .add(HOLLY_FENCE_GATE, PINE_FENCE_GATE, LARCH_FENCE_GATE, ASPEN_FENCE_GATE, KAPOK_FENCE_GATE, MAHOGANY_FENCE_GATE, EUCALYPTUS_FENCE_GATE, BAOBAB_FENCE_GATE, PALO_VERDE_FENCE_GATE, JOSHUA_FENCE_GATE)
                .add(JUNIPER_FENCE_GATE, PALM_FENCE_GATE, EBONY_FENCE_GATE, TEAK_FENCE_GATE, ELM_FENCE_GATE, WILLOW_FENCE_GATE, CYPRESS_FENCE_GATE, SAKURA_FENCE_GATE, MAGNOLIA_FENCE_GATE, JACARANDA_FENCE_GATE);

        getOrCreateTagBuilder(FENCES)
                .add(MAPLE_FENCE, POPLAR_FENCE, BEECH_FENCE, HICKORY_FENCE, WALNUT_FENCE, CHESTNUT_FENCE, CEDAR_FENCE, REDWOOD_FENCE, FIR_FENCE, HEMLOCK_FENCE)
                .add(HOLLY_FENCE, PINE_FENCE, LARCH_FENCE, ASPEN_FENCE, KAPOK_FENCE, MAHOGANY_FENCE, EUCALYPTUS_FENCE, BAOBAB_FENCE, PALO_VERDE_FENCE, JOSHUA_FENCE)
                .add(JUNIPER_FENCE, PALM_FENCE, EBONY_FENCE, TEAK_FENCE, ELM_FENCE, WILLOW_FENCE, CYPRESS_FENCE, SAKURA_FENCE, MAGNOLIA_FENCE, JACARANDA_FENCE);

        getOrCreateTagBuilder(FLOWERS)
                .add(LAVENDER, PURPLE_PETALS);

        getOrCreateTagBuilder(GOLD_ORES)
                .add(GRANITE_GOLD_ORE, DIORITE_GOLD_ORE, ANDESITE_GOLD_ORE, TUFF_GOLD_ORE, GNEISS_GOLD_ORE, SHALE_GOLD_ORE, LIMESTONE_GOLD_ORE, MARBLE_GOLD_ORE, GABBRO_GOLD_ORE, PHYLLITE_GOLD_ORE);

        getOrCreateTagBuilder(INSIDE_STEP_SOUND_BLOCKS)
                .add(PURPLE_PETALS);

        getOrCreateTagBuilder(IRON_ORES)
                .add(GRANITE_IRON_ORE, DIORITE_IRON_ORE, ANDESITE_IRON_ORE, TUFF_IRON_ORE, GNEISS_IRON_ORE, SHALE_IRON_ORE, LIMESTONE_IRON_ORE, MARBLE_IRON_ORE, GABBRO_IRON_ORE, PHYLLITE_IRON_ORE);

        getOrCreateTagBuilder(LAPIS_ORES)
                .add(GRANITE_LAPIS_ORE, DIORITE_LAPIS_ORE, ANDESITE_LAPIS_ORE, TUFF_LAPIS_ORE, GNEISS_LAPIS_ORE, SHALE_LAPIS_ORE, LIMESTONE_LAPIS_ORE, MARBLE_LAPIS_ORE, GABBRO_LAPIS_ORE, PHYLLITE_LAPIS_ORE);

        getOrCreateTagBuilder(LEAVES)
                .add(MAPLE_LEAVES, POPLAR_LEAVES, BEECH_LEAVES, HICKORY_LEAVES, WALNUT_LEAVES, CHESTNUT_LEAVES, CEDAR_LEAVES, REDWOOD_LEAVES, FIR_LEAVES, HEMLOCK_LEAVES)
                .add(HOLLY_LEAVES, PINE_LEAVES, LARCH_LEAVES, ASPEN_LEAVES, KAPOK_LEAVES, MAHOGANY_LEAVES, EUCALYPTUS_LEAVES, BAOBAB_LEAVES, PALO_VERDE_LEAVES, JOSHUA_LEAVES)
                .add(JUNIPER_LEAVES, PALM_LEAVES, EBONY_LEAVES, TEAK_LEAVES, ELM_LEAVES, WILLOW_LEAVES, CYPRESS_LEAVES, SAKURA_LEAVES, MAGNOLIA_LEAVES, JACARANDA_LEAVES);

        getOrCreateTagBuilder(MAINTAINS_FARMLAND)
                .add(ARTICHOKES, BROCCOLI, CABBAGE, CANTALOUPE, CAULIFLOWER, CELERY, CUCUMBERS, EGGPLANT, JALAPENOS, KALE, LETTUCE, ONIONS, PARSNIPS, PEAS, PEPPERS, RADISHES, SPINACH, TURNIPS);

        getOrCreateTagBuilder(NEEDS_IRON_TOOL)
                .addOptionalTag(DIAMOND_ORES)
                .addOptionalTag(EMERALD_ORES)
                .addOptionalTag(GOLD_ORES)
                .addOptionalTag(REDSTONE_ORES);

        getOrCreateTagBuilder(NEEDS_STONE_TOOL)
                .addOptionalTag(COPPER_ORES)
                .addOptionalTag(IRON_ORES)
                .addOptionalTag(LAPIS_ORES);

        getOrCreateTagBuilder(OVERWORLD_NATURAL_LOGS)
                .add(MAPLE_LOG, POPLAR_LOG, BEECH_LOG, HICKORY_LOG, WALNUT_LOG, CHESTNUT_LOG, CEDAR_LOG, REDWOOD_LOG, FIR_LOG, HEMLOCK_LOG)
                .add(HOLLY_LOG, PINE_LOG, LARCH_LOG, ASPEN_LOG, KAPOK_LOG, MAHOGANY_LOG, EUCALYPTUS_LOG, BAOBAB_LOG, PALO_VERDE_LOG, JOSHUA_LOG)
                .add(JUNIPER_LOG, PALM_LOG, EBONY_LOG, TEAK_LOG, ELM_LOG, WILLOW_LOG, CYPRESS_LOG, SAKURA_LOG, MAGNOLIA_LOG, JACARANDA_LOG);

        getOrCreateTagBuilder(PLANKS)
                .add(MAPLE_PLANKS, POPLAR_PLANKS, BEECH_PLANKS, HICKORY_PLANKS, WALNUT_PLANKS, CHESTNUT_PLANKS, CEDAR_PLANKS, REDWOOD_PLANKS, FIR_PLANKS, HEMLOCK_PLANKS)
                .add(HOLLY_PLANKS, PINE_PLANKS, LARCH_PLANKS, ASPEN_PLANKS, KAPOK_PLANKS, MAHOGANY_PLANKS, EUCALYPTUS_PLANKS, BAOBAB_PLANKS, PALO_VERDE_PLANKS, JOSHUA_PLANKS)
                .add(JUNIPER_PLANKS, PALM_PLANKS, EBONY_PLANKS, TEAK_PLANKS, ELM_PLANKS, WILLOW_PLANKS, CYPRESS_PLANKS, SAKURA_PLANKS, MAGNOLIA_PLANKS, JACARANDA_PLANKS);

        getOrCreateTagBuilder(REDSTONE_ORES)
                .add(GRANITE_REDSTONE_ORE, DIORITE_REDSTONE_ORE, ANDESITE_REDSTONE_ORE, TUFF_REDSTONE_ORE, GNEISS_REDSTONE_ORE, SHALE_REDSTONE_ORE, LIMESTONE_REDSTONE_ORE, MARBLE_REDSTONE_ORE, GABBRO_REDSTONE_ORE, PHYLLITE_REDSTONE_ORE);

        getOrCreateTagBuilder(REPLACEABLE)
                .add(SHORT_PRAIRIE_GRASS, TALL_PRAIRIE_GRASS);

        getOrCreateTagBuilder(REPLACEABLE_BY_TREES)
                .add(SHORT_PRAIRIE_GRASS, TALL_PRAIRIE_GRASS, CATTAIL, LAVENDER);

        getOrCreateTagBuilder(SAPLINGS)
                .add(MAPLE_SAPLING, POPLAR_SAPLING, BEECH_SAPLING, HICKORY_SAPLING, WALNUT_SAPLING, CHESTNUT_SAPLING, CEDAR_SAPLING, REDWOOD_SAPLING, FIR_SAPLING, HEMLOCK_SAPLING)
                .add(HOLLY_SAPLING, PINE_SAPLING, LARCH_SAPLING, ASPEN_SAPLING, KAPOK_SAPLING, MAHOGANY_SAPLING, EUCALYPTUS_SAPLING, BAOBAB_SAPLING, PALO_VERDE_SAPLING, JOSHUA_SAPLING)
                .add(JUNIPER_SAPLING, PALM_SAPLING, EBONY_SAPLING, TEAK_SAPLING, ELM_SAPLING, WILLOW_SAPLING, CYPRESS_SAPLING, SAKURA_SAPLING, MAGNOLIA_SAPLING, JACARANDA_SAPLING);

        getOrCreateTagBuilder(SLABS)
                .add(GRANITE_BRICK_SLAB, MOSSY_GRANITE_BRICK_SLAB, DIORITE_BRICK_SLAB, MOSSY_DIORITE_BRICK_SLAB, ANDESITE_BRICK_SLAB, MOSSY_ANDESITE_BRICK_SLAB)
                .add(GNEISS_SLAB, POLISHED_GNEISS_SLAB, GNEISS_BRICK_SLAB, MOSSY_GNEISS_BRICK_SLAB)
                .add(SHALE_SLAB, POLISHED_SHALE_SLAB, SHALE_BRICK_SLAB, MOSSY_SHALE_BRICK_SLAB)
                .add(LIMESTONE_SLAB, POLISHED_LIMESTONE_SLAB, LIMESTONE_BRICK_SLAB, MOSSY_LIMESTONE_BRICK_SLAB)
                .add(MARBLE_SLAB, POLISHED_MARBLE_SLAB, MARBLE_BRICK_SLAB, MOSSY_MARBLE_BRICK_SLAB)
                .add(GABBRO_SLAB, POLISHED_GABBRO_SLAB, GABBRO_BRICK_SLAB, MOSSY_GABBRO_BRICK_SLAB)
                .add(PHYLLITE_SLAB, POLISHED_PHYLLITE_SLAB, PHYLLITE_BRICK_SLAB, MOSSY_PHYLLITE_BRICK_SLAB)
                .add(CALCITE_SLAB, POLISHED_CALCITE_SLAB, CALCITE_BRICK_SLAB, DRIPSTONE_SLAB, POLISHED_DRIPSTONE_SLAB, DRIPSTONE_BRICK_SLAB)
                .add(ROUGH_SANDSTONE_SLAB, ROUGH_RED_SANDSTONE_SLAB)
                .add(FROSTED_SANDSTONE_SLAB, CUT_FROSTED_SANDSTONE_SLAB, SMOOTH_FROSTED_SANDSTONE_SLAB, ROUGH_FROSTED_SANDSTONE_SLAB)
                .add(CHARRED_SANDSTONE_SLAB, CUT_CHARRED_SANDSTONE_SLAB, SMOOTH_CHARRED_SANDSTONE_SLAB, ROUGH_CHARRED_SANDSTONE_SLAB)
                .add(BLUE_NETHER_BRICK_SLAB, QUARTZ_BRICK_SLAB)
                .add(AMETHYST_SLAB, AMETHYST_BRICK_SLAB, AMETHYST_TILE_SLAB, DOLOMITE_SLAB, DOLOMITE_BRICK_SLAB, DOLOMITE_TILE_SLAB, GYPSUM_SLAB, GYPSUM_BRICK_SLAB, GYPSUM_TILE_SLAB)
                .add(WHITE_CONCRETE_SLAB, LIGHT_GRAY_CONCRETE_SLAB, GRAY_CONCRETE_SLAB, BLACK_CONCRETE_SLAB, BROWN_CONCRETE_SLAB, RED_CONCRETE_SLAB, ORANGE_CONCRETE_SLAB, YELLOW_CONCRETE_SLAB)
                .add(LIME_CONCRETE_SLAB, GREEN_CONCRETE_SLAB, CYAN_CONCRETE_SLAB, LIGHT_BLUE_CONCRETE_SLAB, BLUE_CONCRETE_SLAB, PURPLE_CONCRETE_SLAB, MAGENTA_CONCRETE_SLAB, PINK_CONCRETE_SLAB)
                .add(TERRACOTTA_SLAB, WHITE_TERRACOTTA_SLAB, LIGHT_GRAY_TERRACOTTA_SLAB, GRAY_TERRACOTTA_SLAB, BLACK_TERRACOTTA_SLAB, BROWN_TERRACOTTA_SLAB, RED_TERRACOTTA_SLAB, ORANGE_TERRACOTTA_SLAB, YELLOW_TERRACOTTA_SLAB)
                .add(LIME_TERRACOTTA_SLAB, GREEN_TERRACOTTA_SLAB, CYAN_TERRACOTTA_SLAB, LIGHT_BLUE_TERRACOTTA_SLAB, BLUE_TERRACOTTA_SLAB, PURPLE_TERRACOTTA_SLAB, MAGENTA_TERRACOTTA_SLAB, PINK_TERRACOTTA_SLAB)
                .add(TERRACOTTA_BRICK_SLAB, WHITE_TERRACOTTA_BRICK_SLAB, LIGHT_GRAY_TERRACOTTA_BRICK_SLAB, GRAY_TERRACOTTA_BRICK_SLAB, BLACK_TERRACOTTA_BRICK_SLAB, BROWN_TERRACOTTA_BRICK_SLAB, RED_TERRACOTTA_BRICK_SLAB, ORANGE_TERRACOTTA_BRICK_SLAB, YELLOW_TERRACOTTA_BRICK_SLAB)
                .add(LIME_TERRACOTTA_BRICK_SLAB, GREEN_TERRACOTTA_BRICK_SLAB, CYAN_TERRACOTTA_BRICK_SLAB, LIGHT_BLUE_TERRACOTTA_BRICK_SLAB, BLUE_TERRACOTTA_BRICK_SLAB, PURPLE_TERRACOTTA_BRICK_SLAB, MAGENTA_TERRACOTTA_BRICK_SLAB, PINK_TERRACOTTA_BRICK_SLAB)
                .add(CHALK_SLAB, WHITE_CHALK_SLAB, LIGHT_GRAY_CHALK_SLAB, GRAY_CHALK_SLAB, BLACK_CHALK_SLAB, BROWN_CHALK_SLAB, RED_CHALK_SLAB, ORANGE_CHALK_SLAB, YELLOW_CHALK_SLAB)
                .add(LIME_CHALK_SLAB, GREEN_CHALK_SLAB, CYAN_CHALK_SLAB, LIGHT_BLUE_CHALK_SLAB, BLUE_CHALK_SLAB, PURPLE_CHALK_SLAB, MAGENTA_CHALK_SLAB, PINK_CHALK_SLAB)
                .add(CHALK_BRICK_SLAB, WHITE_CHALK_BRICK_SLAB, LIGHT_GRAY_CHALK_BRICK_SLAB, GRAY_CHALK_BRICK_SLAB, BLACK_CHALK_BRICK_SLAB, BROWN_CHALK_BRICK_SLAB, RED_CHALK_BRICK_SLAB, ORANGE_CHALK_BRICK_SLAB, YELLOW_CHALK_BRICK_SLAB)
                .add(LIME_CHALK_BRICK_SLAB, GREEN_CHALK_BRICK_SLAB, CYAN_CHALK_BRICK_SLAB, LIGHT_BLUE_CHALK_BRICK_SLAB, BLUE_CHALK_BRICK_SLAB, PURPLE_CHALK_BRICK_SLAB, MAGENTA_CHALK_BRICK_SLAB, PINK_CHALK_BRICK_SLAB);

        getOrCreateTagBuilder(SMELTS_TO_GLASS)
                .add(FROSTED_SAND, CHARRED_SAND);

        getOrCreateTagBuilder(STAIRS)
                .add(SMOOTH_STONE_STAIRS, GRANITE_BRICK_STAIRS, MOSSY_GRANITE_BRICK_STAIRS, DIORITE_BRICK_STAIRS, MOSSY_DIORITE_BRICK_STAIRS, ANDESITE_BRICK_STAIRS, MOSSY_ANDESITE_BRICK_STAIRS)
                .add(GNEISS_STAIRS, POLISHED_GNEISS_STAIRS, GNEISS_BRICK_STAIRS, MOSSY_GNEISS_BRICK_STAIRS)
                .add(SHALE_STAIRS, POLISHED_SHALE_STAIRS, SHALE_BRICK_STAIRS, MOSSY_SHALE_BRICK_STAIRS)
                .add(LIMESTONE_STAIRS, POLISHED_LIMESTONE_STAIRS, LIMESTONE_BRICK_STAIRS, MOSSY_LIMESTONE_BRICK_STAIRS)
                .add(MARBLE_STAIRS, POLISHED_MARBLE_STAIRS, MARBLE_BRICK_STAIRS, MOSSY_MARBLE_BRICK_STAIRS)
                .add(GABBRO_STAIRS, POLISHED_GABBRO_STAIRS, GABBRO_BRICK_STAIRS, MOSSY_GABBRO_BRICK_STAIRS)
                .add(PHYLLITE_STAIRS, POLISHED_PHYLLITE_STAIRS, PHYLLITE_BRICK_STAIRS, MOSSY_PHYLLITE_BRICK_STAIRS)
                .add(CALCITE_STAIRS, POLISHED_CALCITE_STAIRS, CALCITE_BRICK_STAIRS, DRIPSTONE_STAIRS, POLISHED_DRIPSTONE_STAIRS, DRIPSTONE_BRICK_STAIRS)
                .add(CUT_SANDSTONE_STAIRS, ROUGH_SANDSTONE_STAIRS, CUT_RED_SANDSTONE_STAIRS, ROUGH_RED_SANDSTONE_STAIRS)
                .add(FROSTED_SANDSTONE_STAIRS, CUT_FROSTED_SANDSTONE_STAIRS, SMOOTH_FROSTED_SANDSTONE_STAIRS, ROUGH_FROSTED_SANDSTONE_STAIRS)
                .add(CHARRED_SANDSTONE_STAIRS, CUT_CHARRED_SANDSTONE_STAIRS, SMOOTH_CHARRED_SANDSTONE_STAIRS, ROUGH_CHARRED_SANDSTONE_STAIRS)
                .add(BLUE_NETHER_BRICK_STAIRS, QUARTZ_BRICK_STAIRS)
                .add(AMETHYST_STAIRS, AMETHYST_BRICK_STAIRS, AMETHYST_TILE_STAIRS, DOLOMITE_STAIRS, DOLOMITE_BRICK_STAIRS, DOLOMITE_TILE_STAIRS, GYPSUM_STAIRS, GYPSUM_BRICK_STAIRS, GYPSUM_TILE_STAIRS)
                .add(WHITE_CONCRETE_STAIRS, LIGHT_GRAY_CONCRETE_STAIRS, GRAY_CONCRETE_STAIRS, BLACK_CONCRETE_STAIRS, BROWN_CONCRETE_STAIRS, RED_CONCRETE_STAIRS, ORANGE_CONCRETE_STAIRS, YELLOW_CONCRETE_STAIRS)
                .add(LIME_CONCRETE_STAIRS, GREEN_CONCRETE_STAIRS, CYAN_CONCRETE_STAIRS, LIGHT_BLUE_CONCRETE_STAIRS, BLUE_CONCRETE_STAIRS, PURPLE_CONCRETE_STAIRS, MAGENTA_CONCRETE_STAIRS, PINK_CONCRETE_STAIRS)
                .add(TERRACOTTA_STAIRS, WHITE_TERRACOTTA_STAIRS, LIGHT_GRAY_TERRACOTTA_STAIRS, GRAY_TERRACOTTA_STAIRS, BLACK_TERRACOTTA_STAIRS, BROWN_TERRACOTTA_STAIRS, RED_TERRACOTTA_STAIRS, ORANGE_TERRACOTTA_STAIRS, YELLOW_TERRACOTTA_STAIRS)
                .add(LIME_TERRACOTTA_STAIRS, GREEN_TERRACOTTA_STAIRS, CYAN_TERRACOTTA_STAIRS, LIGHT_BLUE_TERRACOTTA_STAIRS, BLUE_TERRACOTTA_STAIRS, PURPLE_TERRACOTTA_STAIRS, MAGENTA_TERRACOTTA_STAIRS, PINK_TERRACOTTA_STAIRS)
                .add(TERRACOTTA_BRICK_STAIRS, WHITE_TERRACOTTA_BRICK_STAIRS, LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS, GRAY_TERRACOTTA_BRICK_STAIRS, BLACK_TERRACOTTA_BRICK_STAIRS, BROWN_TERRACOTTA_BRICK_STAIRS, RED_TERRACOTTA_BRICK_STAIRS, ORANGE_TERRACOTTA_BRICK_STAIRS, YELLOW_TERRACOTTA_BRICK_STAIRS)
                .add(LIME_TERRACOTTA_BRICK_STAIRS, GREEN_TERRACOTTA_BRICK_STAIRS, CYAN_TERRACOTTA_BRICK_STAIRS, LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS, BLUE_TERRACOTTA_BRICK_STAIRS, PURPLE_TERRACOTTA_BRICK_STAIRS, MAGENTA_TERRACOTTA_BRICK_STAIRS, PINK_TERRACOTTA_BRICK_STAIRS)
                .add(CHALK_STAIRS, WHITE_CHALK_STAIRS, LIGHT_GRAY_CHALK_STAIRS, GRAY_CHALK_STAIRS, BLACK_CHALK_STAIRS, BROWN_CHALK_STAIRS, RED_CHALK_STAIRS, ORANGE_CHALK_STAIRS, YELLOW_CHALK_STAIRS)
                .add(LIME_CHALK_STAIRS, GREEN_CHALK_STAIRS, CYAN_CHALK_STAIRS, LIGHT_BLUE_CHALK_STAIRS, BLUE_CHALK_STAIRS, PURPLE_CHALK_STAIRS, MAGENTA_CHALK_STAIRS, PINK_CHALK_STAIRS)
                .add(CHALK_BRICK_STAIRS, WHITE_CHALK_BRICK_STAIRS, LIGHT_GRAY_CHALK_BRICK_STAIRS, GRAY_CHALK_BRICK_STAIRS, BLACK_CHALK_BRICK_STAIRS, BROWN_CHALK_BRICK_STAIRS, RED_CHALK_BRICK_STAIRS, ORANGE_CHALK_BRICK_STAIRS, YELLOW_CHALK_BRICK_STAIRS)
                .add(LIME_CHALK_BRICK_STAIRS, GREEN_CHALK_BRICK_STAIRS, CYAN_CHALK_BRICK_STAIRS, LIGHT_BLUE_CHALK_BRICK_STAIRS, BLUE_CHALK_BRICK_STAIRS, PURPLE_CHALK_BRICK_STAIRS, MAGENTA_CHALK_BRICK_STAIRS, PINK_CHALK_BRICK_STAIRS);

        getOrCreateTagBuilder(STANDING_SIGNS)
                .add(MAPLE_SIGN, POPLAR_SIGN, BEECH_SIGN, HICKORY_SIGN, WALNUT_SIGN, CHESTNUT_SIGN, CEDAR_SIGN, REDWOOD_SIGN, FIR_SIGN, HEMLOCK_SIGN)
                .add(HOLLY_SIGN, PINE_SIGN, LARCH_SIGN, ASPEN_SIGN, KAPOK_SIGN, MAHOGANY_SIGN, EUCALYPTUS_SIGN, BAOBAB_SIGN, PALO_VERDE_SIGN, JOSHUA_SIGN)
                .add(JUNIPER_SIGN, PALM_SIGN, EBONY_SIGN, TEAK_SIGN, ELM_SIGN, WILLOW_SIGN, CYPRESS_SIGN, SAKURA_SIGN, MAGNOLIA_SIGN, JACARANDA_SIGN);

        getOrCreateTagBuilder(STONE_BUTTONS)
                .add(POLISHED_GRANITE_BUTTON, POLISHED_DIORITE_BUTTON, POLISHED_ANDESITE_BUTTON, POLISHED_GNEISS_BUTTON, POLISHED_SHALE_BUTTON, POLISHED_LIMESTONE_BUTTON, POLISHED_MARBLE_BUTTON, POLISHED_GABBRO_BUTTON, POLISHED_PHYLLITE_BUTTON);

        getOrCreateTagBuilder(STONE_PRESSURE_PLATES)
                .add(POLISHED_GRANITE_PRESSURE_PLATE, POLISHED_DIORITE_PRESSURE_PLATE, POLISHED_ANDESITE_PRESSURE_PLATE, POLISHED_GNEISS_PRESSURE_PLATE, POLISHED_SHALE_PRESSURE_PLATE, POLISHED_LIMESTONE_PRESSURE_PLATE, POLISHED_MARBLE_PRESSURE_PLATE, POLISHED_GABBRO_PRESSURE_PLATE, POLISHED_PHYLLITE_PRESSURE_PLATE);

        getOrCreateTagBuilder(WALLS)
                .add(STONE_WALL, SMOOTH_STONE_WALL, POLISHED_GRANITE_WALL, GRANITE_BRICK_WALL, MOSSY_GRANITE_BRICK_WALL, POLISHED_DIORITE_WALL, DIORITE_BRICK_WALL, MOSSY_DIORITE_BRICK_WALL, POLISHED_ANDESITE_WALL, ANDESITE_BRICK_WALL, MOSSY_ANDESITE_BRICK_WALL)
                .add(GNEISS_WALL, POLISHED_GNEISS_WALL, GNEISS_BRICK_WALL, MOSSY_GNEISS_BRICK_WALL)
                .add(SHALE_WALL, POLISHED_SHALE_WALL, SHALE_BRICK_WALL, MOSSY_SHALE_BRICK_WALL)
                .add(LIMESTONE_WALL, POLISHED_LIMESTONE_WALL, LIMESTONE_BRICK_WALL, MOSSY_LIMESTONE_BRICK_WALL)
                .add(MARBLE_WALL, POLISHED_MARBLE_WALL, MARBLE_BRICK_WALL, MOSSY_MARBLE_BRICK_WALL)
                .add(GABBRO_WALL, POLISHED_GABBRO_WALL, GABBRO_BRICK_WALL, MOSSY_GABBRO_BRICK_WALL)
                .add(PHYLLITE_WALL, POLISHED_PHYLLITE_WALL, PHYLLITE_BRICK_WALL, MOSSY_PHYLLITE_BRICK_WALL)
                .add(CALCITE_WALL, POLISHED_CALCITE_WALL, CALCITE_BRICK_WALL, DRIPSTONE_WALL, POLISHED_DRIPSTONE_WALL, DRIPSTONE_BRICK_WALL)
                .add(CUT_SANDSTONE_WALL, SMOOTH_SANDSTONE_WALL, ROUGH_SANDSTONE_WALL, CUT_RED_SANDSTONE_WALL, SMOOTH_RED_SANDSTONE_WALL, ROUGH_RED_SANDSTONE_WALL)
                .add(FROSTED_SANDSTONE_WALL, CUT_FROSTED_SANDSTONE_WALL, SMOOTH_FROSTED_SANDSTONE_WALL, ROUGH_FROSTED_SANDSTONE_WALL)
                .add(CHARRED_SANDSTONE_WALL, CUT_CHARRED_SANDSTONE_WALL, SMOOTH_CHARRED_SANDSTONE_WALL, ROUGH_CHARRED_SANDSTONE_WALL)
                .add(PRISMARINE_BRICK_WALL, DARK_PRISMARINE_WALL, BLUE_NETHER_BRICK_WALL, QUARTZ_WALL, QUARTZ_BRICK_WALL, SMOOTH_QUARTZ_WALL)
                .add(AMETHYST_WALL, AMETHYST_BRICK_WALL, AMETHYST_TILE_WALL, DOLOMITE_WALL, DOLOMITE_BRICK_WALL, DOLOMITE_TILE_WALL, GYPSUM_WALL, GYPSUM_BRICK_WALL, GYPSUM_TILE_WALL)
                .add(WHITE_CONCRETE_WALL, LIGHT_GRAY_CONCRETE_WALL, GRAY_CONCRETE_WALL, BLACK_CONCRETE_WALL, BROWN_CONCRETE_WALL, RED_CONCRETE_WALL, ORANGE_CONCRETE_WALL, YELLOW_CONCRETE_WALL)
                .add(LIME_CONCRETE_WALL, GREEN_CONCRETE_WALL, CYAN_CONCRETE_WALL, LIGHT_BLUE_CONCRETE_WALL, BLUE_CONCRETE_WALL, PURPLE_CONCRETE_WALL, MAGENTA_CONCRETE_WALL, PINK_CONCRETE_WALL)
                .add(TERRACOTTA_WALL, WHITE_TERRACOTTA_WALL, LIGHT_GRAY_TERRACOTTA_WALL, GRAY_TERRACOTTA_WALL, BLACK_TERRACOTTA_WALL, BROWN_TERRACOTTA_WALL, RED_TERRACOTTA_WALL, ORANGE_TERRACOTTA_WALL, YELLOW_TERRACOTTA_WALL)
                .add(LIME_TERRACOTTA_WALL, GREEN_TERRACOTTA_WALL, CYAN_TERRACOTTA_WALL, LIGHT_BLUE_TERRACOTTA_WALL, BLUE_TERRACOTTA_WALL, PURPLE_TERRACOTTA_WALL, MAGENTA_TERRACOTTA_WALL, PINK_TERRACOTTA_WALL)
                .add(TERRACOTTA_BRICK_WALL, WHITE_TERRACOTTA_BRICK_WALL, LIGHT_GRAY_TERRACOTTA_BRICK_WALL, GRAY_TERRACOTTA_BRICK_WALL, BLACK_TERRACOTTA_BRICK_WALL, BROWN_TERRACOTTA_BRICK_WALL, RED_TERRACOTTA_BRICK_WALL, ORANGE_TERRACOTTA_BRICK_WALL, YELLOW_TERRACOTTA_BRICK_WALL)
                .add(LIME_TERRACOTTA_BRICK_WALL, GREEN_TERRACOTTA_BRICK_WALL, CYAN_TERRACOTTA_BRICK_WALL, LIGHT_BLUE_TERRACOTTA_BRICK_WALL, BLUE_TERRACOTTA_BRICK_WALL, PURPLE_TERRACOTTA_BRICK_WALL, MAGENTA_TERRACOTTA_BRICK_WALL, PINK_TERRACOTTA_BRICK_WALL)
                .add(CHALK_WALL, WHITE_CHALK_WALL, LIGHT_GRAY_CHALK_WALL, GRAY_CHALK_WALL, BLACK_CHALK_WALL, BROWN_CHALK_WALL, RED_CHALK_WALL, ORANGE_CHALK_WALL, YELLOW_CHALK_WALL)
                .add(LIME_CHALK_WALL, GREEN_CHALK_WALL, CYAN_CHALK_WALL, LIGHT_BLUE_CHALK_WALL, BLUE_CHALK_WALL, PURPLE_CHALK_WALL, MAGENTA_CHALK_WALL, PINK_CHALK_WALL)
                .add(CHALK_BRICK_WALL, WHITE_CHALK_BRICK_WALL, LIGHT_GRAY_CHALK_BRICK_WALL, GRAY_CHALK_BRICK_WALL, BLACK_CHALK_BRICK_WALL, BROWN_CHALK_BRICK_WALL, RED_CHALK_BRICK_WALL, ORANGE_CHALK_BRICK_WALL, YELLOW_CHALK_BRICK_WALL)
                .add(LIME_CHALK_BRICK_WALL, GREEN_CHALK_BRICK_WALL, CYAN_CHALK_BRICK_WALL, LIGHT_BLUE_CHALK_BRICK_WALL, BLUE_CHALK_BRICK_WALL, PURPLE_CHALK_BRICK_WALL, MAGENTA_CHALK_BRICK_WALL, PINK_CHALK_BRICK_WALL);

        getOrCreateTagBuilder(WALL_HANGING_SIGNS)
                .add(MAPLE_WALL_HANGING_SIGN, POPLAR_WALL_HANGING_SIGN, BEECH_WALL_HANGING_SIGN, HICKORY_WALL_HANGING_SIGN, WALNUT_WALL_HANGING_SIGN, CHESTNUT_WALL_HANGING_SIGN, CEDAR_WALL_HANGING_SIGN, REDWOOD_WALL_HANGING_SIGN, FIR_WALL_HANGING_SIGN, HEMLOCK_WALL_HANGING_SIGN)
                .add(HOLLY_WALL_HANGING_SIGN, PINE_WALL_HANGING_SIGN, LARCH_WALL_HANGING_SIGN, ASPEN_WALL_HANGING_SIGN, KAPOK_WALL_HANGING_SIGN, MAHOGANY_WALL_HANGING_SIGN, EUCALYPTUS_WALL_HANGING_SIGN, BAOBAB_WALL_HANGING_SIGN, PALO_VERDE_WALL_HANGING_SIGN, JOSHUA_WALL_HANGING_SIGN)
                .add(JUNIPER_WALL_HANGING_SIGN, PALM_WALL_HANGING_SIGN, EBONY_WALL_HANGING_SIGN, TEAK_WALL_HANGING_SIGN, ELM_WALL_HANGING_SIGN, WILLOW_WALL_HANGING_SIGN, CYPRESS_WALL_HANGING_SIGN, SAKURA_WALL_HANGING_SIGN, MAGNOLIA_WALL_HANGING_SIGN, JACARANDA_WALL_HANGING_SIGN);

        getOrCreateTagBuilder(WALL_SIGNS)
                .add(MAPLE_WALL_SIGN, POPLAR_WALL_SIGN, BEECH_WALL_SIGN, HICKORY_WALL_SIGN, WALNUT_WALL_SIGN, CHESTNUT_WALL_SIGN, CEDAR_WALL_SIGN, REDWOOD_WALL_SIGN, FIR_WALL_SIGN, HEMLOCK_WALL_SIGN)
                .add(HOLLY_WALL_SIGN, PINE_WALL_SIGN, LARCH_WALL_SIGN, ASPEN_WALL_SIGN, KAPOK_WALL_SIGN, MAHOGANY_WALL_SIGN, EUCALYPTUS_WALL_SIGN, BAOBAB_WALL_SIGN, PALO_VERDE_WALL_SIGN, JOSHUA_WALL_SIGN)
                .add(JUNIPER_WALL_SIGN, PALM_WALL_SIGN, EBONY_WALL_SIGN, TEAK_WALL_SIGN, ELM_WALL_SIGN, WILLOW_WALL_SIGN, CYPRESS_WALL_SIGN, SAKURA_WALL_SIGN, MAGNOLIA_WALL_SIGN, JACARANDA_WALL_SIGN);

        getOrCreateTagBuilder(WOODEN_BUTTONS)
                .add(MAPLE_BUTTON, POPLAR_BUTTON, BEECH_BUTTON, HICKORY_BUTTON, WALNUT_BUTTON, CHESTNUT_BUTTON, CEDAR_BUTTON, REDWOOD_BUTTON, FIR_BUTTON, HEMLOCK_BUTTON)
                .add(HOLLY_BUTTON, PINE_BUTTON, LARCH_BUTTON, ASPEN_BUTTON, KAPOK_BUTTON, MAHOGANY_BUTTON, EUCALYPTUS_BUTTON, BAOBAB_BUTTON, PALO_VERDE_BUTTON, JOSHUA_BUTTON)
                .add(JUNIPER_BUTTON, PALM_BUTTON, EBONY_BUTTON, TEAK_BUTTON, ELM_BUTTON, WILLOW_BUTTON, CYPRESS_BUTTON, SAKURA_BUTTON, MAGNOLIA_BUTTON, JACARANDA_BUTTON);

        getOrCreateTagBuilder(WOODEN_DOORS)
                .add(MAPLE_DOOR, POPLAR_DOOR, BEECH_DOOR, HICKORY_DOOR, WALNUT_DOOR, CHESTNUT_DOOR, CEDAR_DOOR, REDWOOD_DOOR, FIR_DOOR, HEMLOCK_DOOR)
                .add(HOLLY_DOOR, PINE_DOOR, LARCH_DOOR, ASPEN_DOOR, KAPOK_DOOR, MAHOGANY_DOOR, EUCALYPTUS_DOOR, BAOBAB_DOOR, PALO_VERDE_DOOR, JOSHUA_DOOR)
                .add(JUNIPER_DOOR, PALM_DOOR, EBONY_DOOR, TEAK_DOOR, ELM_DOOR, WILLOW_DOOR, CYPRESS_DOOR, SAKURA_DOOR, MAGNOLIA_DOOR, JACARANDA_DOOR);

        getOrCreateTagBuilder(WOODEN_FENCES)
                .add(MAPLE_FENCE, POPLAR_FENCE, BEECH_FENCE, HICKORY_FENCE, WALNUT_FENCE, CHESTNUT_FENCE, CEDAR_FENCE, REDWOOD_FENCE, FIR_FENCE, HEMLOCK_FENCE)
                .add(HOLLY_FENCE, PINE_FENCE, LARCH_FENCE, ASPEN_FENCE, KAPOK_FENCE, MAHOGANY_FENCE, EUCALYPTUS_FENCE, BAOBAB_FENCE, PALO_VERDE_FENCE, JOSHUA_FENCE)
                .add(JUNIPER_FENCE, PALM_FENCE, EBONY_FENCE, TEAK_FENCE, ELM_FENCE, WILLOW_FENCE, CYPRESS_FENCE, SAKURA_FENCE, MAGNOLIA_FENCE, JACARANDA_FENCE);

        getOrCreateTagBuilder(WOODEN_PRESSURE_PLATES)
                .add(MAPLE_PRESSURE_PLATE, POPLAR_PRESSURE_PLATE, BEECH_PRESSURE_PLATE, HICKORY_PRESSURE_PLATE, WALNUT_PRESSURE_PLATE, CHESTNUT_PRESSURE_PLATE, CEDAR_PRESSURE_PLATE, REDWOOD_PRESSURE_PLATE, FIR_PRESSURE_PLATE, HEMLOCK_PRESSURE_PLATE)
                .add(HOLLY_PRESSURE_PLATE, PINE_PRESSURE_PLATE, LARCH_PRESSURE_PLATE, ASPEN_PRESSURE_PLATE, KAPOK_PRESSURE_PLATE, MAHOGANY_PRESSURE_PLATE, EUCALYPTUS_PRESSURE_PLATE, BAOBAB_PRESSURE_PLATE, PALO_VERDE_PRESSURE_PLATE, JOSHUA_PRESSURE_PLATE)
                .add(JUNIPER_PRESSURE_PLATE, PALM_PRESSURE_PLATE, EBONY_PRESSURE_PLATE, TEAK_PRESSURE_PLATE, ELM_PRESSURE_PLATE, WILLOW_PRESSURE_PLATE, CYPRESS_PRESSURE_PLATE, SAKURA_PRESSURE_PLATE, MAGNOLIA_PRESSURE_PLATE, JACARANDA_PRESSURE_PLATE);

        getOrCreateTagBuilder(WOODEN_SLABS)
                .add(MAPLE_SLAB, POPLAR_SLAB, BEECH_SLAB, HICKORY_SLAB, WALNUT_SLAB, CHESTNUT_SLAB, CEDAR_SLAB, REDWOOD_SLAB, FIR_SLAB, HEMLOCK_SLAB)
                .add(HOLLY_SLAB, PINE_SLAB, LARCH_SLAB, ASPEN_SLAB, KAPOK_SLAB, MAHOGANY_SLAB, EUCALYPTUS_SLAB, BAOBAB_SLAB, PALO_VERDE_SLAB, JOSHUA_SLAB)
                .add(JUNIPER_SLAB, PALM_SLAB, EBONY_SLAB, TEAK_SLAB, ELM_SLAB, WILLOW_SLAB, CYPRESS_SLAB, SAKURA_SLAB, MAGNOLIA_SLAB, JACARANDA_SLAB);

        getOrCreateTagBuilder(WOODEN_STAIRS)
                .add(MAPLE_STAIRS, POPLAR_STAIRS, BEECH_STAIRS, HICKORY_STAIRS, WALNUT_STAIRS, CHESTNUT_STAIRS, CEDAR_STAIRS, REDWOOD_STAIRS, FIR_STAIRS, HEMLOCK_STAIRS)
                .add(HOLLY_STAIRS, PINE_STAIRS, LARCH_STAIRS, ASPEN_STAIRS, KAPOK_STAIRS, MAHOGANY_STAIRS, EUCALYPTUS_STAIRS, BAOBAB_STAIRS, PALO_VERDE_STAIRS, JOSHUA_STAIRS)
                .add(JUNIPER_STAIRS, PALM_STAIRS, EBONY_STAIRS, TEAK_STAIRS, ELM_STAIRS, WILLOW_STAIRS, CYPRESS_STAIRS, SAKURA_STAIRS, MAGNOLIA_STAIRS, JACARANDA_STAIRS);

        getOrCreateTagBuilder(WOODEN_TRAPDOORS)
                .add(MAPLE_TRAPDOOR, POPLAR_TRAPDOOR, BEECH_TRAPDOOR, HICKORY_TRAPDOOR, WALNUT_TRAPDOOR, CHESTNUT_TRAPDOOR, CEDAR_TRAPDOOR, REDWOOD_TRAPDOOR, FIR_TRAPDOOR, HEMLOCK_TRAPDOOR)
                .add(HOLLY_TRAPDOOR, PINE_TRAPDOOR, LARCH_TRAPDOOR, ASPEN_TRAPDOOR, KAPOK_TRAPDOOR, MAHOGANY_TRAPDOOR, EUCALYPTUS_TRAPDOOR, BAOBAB_TRAPDOOR, PALO_VERDE_TRAPDOOR, JOSHUA_TRAPDOOR)
                .add(JUNIPER_TRAPDOOR, PALM_TRAPDOOR, EBONY_TRAPDOOR, TEAK_TRAPDOOR, ELM_TRAPDOOR, WILLOW_TRAPDOOR, CYPRESS_TRAPDOOR, SAKURA_TRAPDOOR, MAGNOLIA_TRAPDOOR, JACARANDA_TRAPDOOR);

        getOrCreateTagBuilder(MAPLE_LOGS)
                .add(MAPLE_LOG, MAPLE_WOOD, STRIPPED_MAPLE_LOG, STRIPPED_MAPLE_WOOD);

        getOrCreateTagBuilder(POPLAR_LOGS)
                .add(POPLAR_LOG, POPLAR_WOOD, STRIPPED_POPLAR_LOG, STRIPPED_POPLAR_WOOD);

        getOrCreateTagBuilder(BEECH_LOGS)
                .add(BEECH_LOG, BEECH_WOOD, STRIPPED_BEECH_LOG, STRIPPED_BEECH_WOOD);

        getOrCreateTagBuilder(HICKORY_LOGS)
                .add(HICKORY_LOG, HICKORY_WOOD, STRIPPED_HICKORY_LOG, STRIPPED_HICKORY_WOOD);

        getOrCreateTagBuilder(WALNUT_LOGS)
                .add(WALNUT_LOG, WALNUT_WOOD, STRIPPED_WALNUT_LOG, STRIPPED_WALNUT_WOOD);

        getOrCreateTagBuilder(CHESTNUT_LOGS)
                .add(CHESTNUT_LOG, CHESTNUT_WOOD, STRIPPED_CHESTNUT_LOG, STRIPPED_CHESTNUT_WOOD);

        getOrCreateTagBuilder(CEDAR_LOGS)
                .add(CEDAR_LOG, CEDAR_WOOD, STRIPPED_CEDAR_LOG, STRIPPED_CEDAR_WOOD);

        getOrCreateTagBuilder(REDWOOD_LOGS)
                .add(REDWOOD_LOG, REDWOOD_WOOD, STRIPPED_REDWOOD_LOG, STRIPPED_REDWOOD_WOOD);

        getOrCreateTagBuilder(FIR_LOGS)
                .add(FIR_LOG, FIR_WOOD, STRIPPED_FIR_LOG, STRIPPED_FIR_WOOD);

        getOrCreateTagBuilder(HEMLOCK_LOGS)
                .add(HEMLOCK_LOG, HEMLOCK_WOOD, STRIPPED_HEMLOCK_LOG, STRIPPED_HEMLOCK_WOOD);

        getOrCreateTagBuilder(HOLLY_LOGS)
                .add(HOLLY_LOG, HOLLY_WOOD, STRIPPED_HOLLY_LOG, STRIPPED_HOLLY_WOOD);

        getOrCreateTagBuilder(PINE_LOGS)
                .add(PINE_LOG, PINE_WOOD, STRIPPED_PINE_LOG, STRIPPED_PINE_WOOD);

        getOrCreateTagBuilder(LARCH_LOGS)
                .add(LARCH_LOG, LARCH_WOOD, STRIPPED_LARCH_LOG, STRIPPED_LARCH_WOOD);

        getOrCreateTagBuilder(ASPEN_LOGS)
                .add(ASPEN_LOG, ASPEN_WOOD, STRIPPED_ASPEN_LOG, STRIPPED_ASPEN_WOOD);

        getOrCreateTagBuilder(KAPOK_LOGS)
                .add(KAPOK_LOG, KAPOK_WOOD, STRIPPED_KAPOK_LOG, STRIPPED_KAPOK_WOOD);

        getOrCreateTagBuilder(MAHOGANY_LOGS)
                .add(MAHOGANY_LOG, MAHOGANY_WOOD, STRIPPED_MAHOGANY_LOG, STRIPPED_MAHOGANY_WOOD);

        getOrCreateTagBuilder(EUCALYPTUS_LOGS)
                .add(EUCALYPTUS_LOG, EUCALYPTUS_WOOD, STRIPPED_EUCALYPTUS_LOG, STRIPPED_EUCALYPTUS_WOOD);

        getOrCreateTagBuilder(BAOBAB_LOGS)
                .add(BAOBAB_LOG, BAOBAB_WOOD, STRIPPED_BAOBAB_LOG, STRIPPED_BAOBAB_WOOD);

        getOrCreateTagBuilder(PALO_VERDE_LOGS)
                .add(PALO_VERDE_LOG, PALO_VERDE_WOOD, STRIPPED_PALO_VERDE_LOG, STRIPPED_PALO_VERDE_WOOD);

        getOrCreateTagBuilder(JOSHUA_LOGS)
                .add(JOSHUA_LOG, JOSHUA_WOOD, STRIPPED_JOSHUA_LOG, STRIPPED_JOSHUA_WOOD);

        getOrCreateTagBuilder(JUNIPER_LOGS)
                .add(JUNIPER_LOG, JUNIPER_WOOD, STRIPPED_JUNIPER_LOG, STRIPPED_JUNIPER_WOOD);

        getOrCreateTagBuilder(PALM_LOGS)
                .add(PALM_LOG, PALM_WOOD, STRIPPED_PALM_LOG, STRIPPED_PALM_WOOD);

        getOrCreateTagBuilder(EBONY_LOGS)
                .add(EBONY_LOG, EBONY_WOOD, STRIPPED_EBONY_LOG, STRIPPED_EBONY_WOOD);

        getOrCreateTagBuilder(TEAK_LOGS)
                .add(TEAK_LOG, TEAK_WOOD, STRIPPED_TEAK_LOG, STRIPPED_TEAK_WOOD);

        getOrCreateTagBuilder(ELM_LOGS)
                .add(ELM_LOG, ELM_WOOD, STRIPPED_ELM_LOG, STRIPPED_ELM_WOOD);

        getOrCreateTagBuilder(WILLOW_LOGS)
                .add(WILLOW_LOG, WILLOW_WOOD, STRIPPED_WILLOW_LOG, STRIPPED_WILLOW_WOOD);

        getOrCreateTagBuilder(CYPRESS_LOGS)
                .add(CYPRESS_LOG, CYPRESS_WOOD, STRIPPED_CYPRESS_LOG, STRIPPED_CYPRESS_WOOD);

        getOrCreateTagBuilder(SAKURA_LOGS)
                .add(SAKURA_LOG, SAKURA_WOOD, STRIPPED_SAKURA_LOG, STRIPPED_SAKURA_WOOD);

        getOrCreateTagBuilder(MAGNOLIA_LOGS)
                .add(MAGNOLIA_LOG, MAGNOLIA_WOOD, STRIPPED_MAGNOLIA_LOG, STRIPPED_MAGNOLIA_WOOD);

        getOrCreateTagBuilder(JACARANDA_LOGS)
                .add(JACARANDA_LOG, JACARANDA_WOOD, STRIPPED_JACARANDA_LOG, STRIPPED_JACARANDA_WOOD);

        getOrCreateTagBuilder(LOGS_THAT_BURN)
                .addOptionalTag(MAPLE_LOGS)
                .addOptionalTag(POPLAR_LOGS)
                .addOptionalTag(BEECH_LOGS)
                .addOptionalTag(HICKORY_LOGS)
                .addOptionalTag(WALNUT_LOGS)
                .addOptionalTag(CHESTNUT_LOGS)
                .addOptionalTag(CEDAR_LOGS)
                .addOptionalTag(REDWOOD_LOGS)
                .addOptionalTag(FIR_LOGS)
                .addOptionalTag(HEMLOCK_LOGS)
                .addOptionalTag(HOLLY_LOGS)
                .addOptionalTag(PINE_LOGS)
                .addOptionalTag(LARCH_LOGS)
                .addOptionalTag(ASPEN_LOGS)
                .addOptionalTag(KAPOK_LOGS)
                .addOptionalTag(MAHOGANY_LOGS)
                .addOptionalTag(EUCALYPTUS_LOGS)
                .addOptionalTag(BAOBAB_LOGS)
                .addOptionalTag(PALO_VERDE_LOGS)
                .addOptionalTag(JOSHUA_LOGS)
                .addOptionalTag(JUNIPER_LOGS)
                .addOptionalTag(PALM_LOGS)
                .addOptionalTag(EBONY_LOGS)
                .addOptionalTag(TEAK_LOGS)
                .addOptionalTag(ELM_LOGS)
                .addOptionalTag(WILLOW_LOGS)
                .addOptionalTag(CYPRESS_LOGS)
                .addOptionalTag(SAKURA_LOGS)
                .addOptionalTag(MAGNOLIA_LOGS)
                .addOptionalTag(JACARANDA_LOGS);
    }
}
