package me.withers_overhaul.datagen.fabric;

import me.withers_overhaul.registry.block.WoodBlocks;
import me.withers_overhaul.registry.item.BlockItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.world.biome.Biome;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.CompletableFuture;

import static me.withers_overhaul.registry.block.ColoredBlocks.*;
import static me.withers_overhaul.registry.block.NaturalBlocks.*;
import static me.withers_overhaul.registry.block.StoneBlocks.*;
import static me.withers_overhaul.registry.block.WoodBlocks.*;
import static me.withers_overhaul.registry.item.BasicItems.*;
import static me.withers_overhaul.registry.item.OverhaulItemGroups.WITHERS_OVERHAUL_BLOCKS_KEY;
import static me.withers_overhaul.registry.item.OverhaulItemGroups.WITHERS_OVERHAUL_ITEMS_KEY;
import static me.withers_overhaul.registry.item.OverhaulItems.TOOLTIP_PATH;
import static me.withers_overhaul.world.biome.OverhaulBiomeKeys.*;

public class LangGen extends FabricLanguageProvider {
    public LangGen(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(output, registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup registryLookup, TranslationBuilder translationBuilder) {

        Block[] allBlocks = {
                MAPLE_LOG, MAPLE_WOOD, STRIPPED_MAPLE_LOG, STRIPPED_MAPLE_WOOD, MAPLE_PLANKS, MAPLE_STAIRS, MAPLE_SLAB, MAPLE_FENCE, MAPLE_FENCE_GATE, MAPLE_DOOR, MAPLE_TRAPDOOR, MAPLE_PRESSURE_PLATE, MAPLE_BUTTON, WoodBlocks.MAPLE_SIGN, WoodBlocks.MAPLE_HANGING_SIGN, MAPLE_LEAVES, MAPLE_SAPLING,
                POPLAR_LOG, POPLAR_WOOD, STRIPPED_POPLAR_LOG, STRIPPED_POPLAR_WOOD, POPLAR_PLANKS, POPLAR_STAIRS, POPLAR_SLAB, POPLAR_FENCE, POPLAR_FENCE_GATE, POPLAR_DOOR, POPLAR_TRAPDOOR, POPLAR_PRESSURE_PLATE, POPLAR_BUTTON, WoodBlocks.POPLAR_SIGN, WoodBlocks.POPLAR_HANGING_SIGN, POPLAR_LEAVES, POPLAR_SAPLING,
                BEECH_LOG, BEECH_WOOD, STRIPPED_BEECH_LOG, STRIPPED_BEECH_WOOD, BEECH_PLANKS, BEECH_STAIRS, BEECH_SLAB, BEECH_FENCE, BEECH_FENCE_GATE, BEECH_DOOR, BEECH_TRAPDOOR, BEECH_PRESSURE_PLATE, BEECH_BUTTON, WoodBlocks.BEECH_SIGN, WoodBlocks.BEECH_HANGING_SIGN, BEECH_LEAVES, BEECH_SAPLING,
                HICKORY_LOG, HICKORY_WOOD, STRIPPED_HICKORY_LOG, STRIPPED_HICKORY_WOOD, HICKORY_PLANKS, HICKORY_STAIRS, HICKORY_SLAB, HICKORY_FENCE, HICKORY_FENCE_GATE, HICKORY_DOOR, HICKORY_TRAPDOOR, HICKORY_PRESSURE_PLATE, HICKORY_BUTTON, WoodBlocks.HICKORY_SIGN, WoodBlocks.HICKORY_HANGING_SIGN, HICKORY_LEAVES, HICKORY_SAPLING,
                WALNUT_LOG, WALNUT_WOOD, STRIPPED_WALNUT_LOG, STRIPPED_WALNUT_WOOD, WALNUT_PLANKS, WALNUT_STAIRS, WALNUT_SLAB, WALNUT_FENCE, WALNUT_FENCE_GATE, WALNUT_DOOR, WALNUT_TRAPDOOR, WALNUT_PRESSURE_PLATE, WALNUT_BUTTON, WoodBlocks.WALNUT_SIGN, WoodBlocks.WALNUT_HANGING_SIGN, WALNUT_LEAVES, WALNUT_SAPLING,
                CHESTNUT_LOG, CHESTNUT_WOOD, STRIPPED_CHESTNUT_LOG, STRIPPED_CHESTNUT_WOOD, CHESTNUT_PLANKS, CHESTNUT_STAIRS, CHESTNUT_SLAB, CHESTNUT_FENCE, CHESTNUT_FENCE_GATE, CHESTNUT_DOOR, CHESTNUT_TRAPDOOR, CHESTNUT_PRESSURE_PLATE, CHESTNUT_BUTTON, WoodBlocks.CHESTNUT_SIGN, WoodBlocks.CHESTNUT_HANGING_SIGN, CHESTNUT_LEAVES, CHESTNUT_SAPLING,
                CEDAR_LOG, CEDAR_WOOD, STRIPPED_CEDAR_LOG, STRIPPED_CEDAR_WOOD, CEDAR_PLANKS, CEDAR_STAIRS, CEDAR_SLAB, CEDAR_FENCE, CEDAR_FENCE_GATE, CEDAR_DOOR, CEDAR_TRAPDOOR, CEDAR_PRESSURE_PLATE, CEDAR_BUTTON, WoodBlocks.CEDAR_SIGN, WoodBlocks.CEDAR_HANGING_SIGN, CEDAR_LEAVES, CEDAR_SAPLING,
                REDWOOD_LOG, REDWOOD_WOOD, STRIPPED_REDWOOD_LOG, STRIPPED_REDWOOD_WOOD, REDWOOD_PLANKS, REDWOOD_STAIRS, REDWOOD_SLAB, REDWOOD_FENCE, REDWOOD_FENCE_GATE, REDWOOD_DOOR, REDWOOD_TRAPDOOR, REDWOOD_PRESSURE_PLATE, REDWOOD_BUTTON, WoodBlocks.REDWOOD_SIGN, WoodBlocks.REDWOOD_HANGING_SIGN, REDWOOD_LEAVES, REDWOOD_SAPLING,
                FIR_LOG, FIR_WOOD, STRIPPED_FIR_LOG, STRIPPED_FIR_WOOD, FIR_PLANKS, FIR_STAIRS, FIR_SLAB, FIR_FENCE, FIR_FENCE_GATE, FIR_DOOR, FIR_TRAPDOOR, FIR_PRESSURE_PLATE, FIR_BUTTON, WoodBlocks.FIR_SIGN, WoodBlocks.FIR_HANGING_SIGN, FIR_LEAVES, FIR_SAPLING,
                HEMLOCK_LOG, HEMLOCK_WOOD, STRIPPED_HEMLOCK_LOG, STRIPPED_HEMLOCK_WOOD, HEMLOCK_PLANKS, HEMLOCK_STAIRS, HEMLOCK_SLAB, HEMLOCK_FENCE, HEMLOCK_FENCE_GATE, HEMLOCK_DOOR, HEMLOCK_TRAPDOOR, HEMLOCK_PRESSURE_PLATE, HEMLOCK_BUTTON, WoodBlocks.HEMLOCK_SIGN, WoodBlocks.HEMLOCK_HANGING_SIGN, HEMLOCK_LEAVES, HEMLOCK_SAPLING,
                HOLLY_LOG, HOLLY_WOOD, STRIPPED_HOLLY_LOG, STRIPPED_HOLLY_WOOD, HOLLY_PLANKS, HOLLY_STAIRS, HOLLY_SLAB, HOLLY_FENCE, HOLLY_FENCE_GATE, HOLLY_DOOR, HOLLY_TRAPDOOR, HOLLY_PRESSURE_PLATE, HOLLY_BUTTON, WoodBlocks.HOLLY_SIGN, WoodBlocks.HOLLY_HANGING_SIGN, HOLLY_LEAVES, HOLLY_SAPLING,
                PINE_LOG, PINE_WOOD, STRIPPED_PINE_LOG, STRIPPED_PINE_WOOD, PINE_PLANKS, PINE_STAIRS, PINE_SLAB, PINE_FENCE, PINE_FENCE_GATE, PINE_DOOR, PINE_TRAPDOOR, PINE_PRESSURE_PLATE, PINE_BUTTON, WoodBlocks.PINE_SIGN, WoodBlocks.PINE_HANGING_SIGN, PINE_LEAVES, PINE_SAPLING,
                LARCH_LOG, LARCH_WOOD, STRIPPED_LARCH_LOG, STRIPPED_LARCH_WOOD, LARCH_PLANKS, LARCH_STAIRS, LARCH_SLAB, LARCH_FENCE, LARCH_FENCE_GATE, LARCH_DOOR, LARCH_TRAPDOOR, LARCH_PRESSURE_PLATE, LARCH_BUTTON, WoodBlocks.LARCH_SIGN, WoodBlocks.LARCH_HANGING_SIGN, LARCH_LEAVES, LARCH_SAPLING,
                ASPEN_LOG, ASPEN_WOOD, STRIPPED_ASPEN_LOG, STRIPPED_ASPEN_WOOD, ASPEN_PLANKS, ASPEN_STAIRS, ASPEN_SLAB, ASPEN_FENCE, ASPEN_FENCE_GATE, ASPEN_DOOR, ASPEN_TRAPDOOR, ASPEN_PRESSURE_PLATE, ASPEN_BUTTON, WoodBlocks.ASPEN_SIGN, WoodBlocks.ASPEN_HANGING_SIGN, ASPEN_LEAVES, ASPEN_SAPLING,
                KAPOK_LOG, KAPOK_WOOD, STRIPPED_KAPOK_LOG, STRIPPED_KAPOK_WOOD, KAPOK_PLANKS, KAPOK_STAIRS, KAPOK_SLAB, KAPOK_FENCE, KAPOK_FENCE_GATE, KAPOK_DOOR, KAPOK_TRAPDOOR, KAPOK_PRESSURE_PLATE, KAPOK_BUTTON, WoodBlocks.KAPOK_SIGN, WoodBlocks.KAPOK_HANGING_SIGN, KAPOK_LEAVES, KAPOK_SAPLING,
                MAHOGANY_LOG, MAHOGANY_WOOD, STRIPPED_MAHOGANY_LOG, STRIPPED_MAHOGANY_WOOD, MAHOGANY_PLANKS, MAHOGANY_STAIRS, MAHOGANY_SLAB, MAHOGANY_FENCE, MAHOGANY_FENCE_GATE, MAHOGANY_DOOR, MAHOGANY_TRAPDOOR, MAHOGANY_PRESSURE_PLATE, MAHOGANY_BUTTON, WoodBlocks.MAHOGANY_SIGN, WoodBlocks.MAHOGANY_HANGING_SIGN, MAHOGANY_LEAVES, MAHOGANY_SAPLING,
                EUCALYPTUS_LOG, EUCALYPTUS_WOOD, STRIPPED_EUCALYPTUS_LOG, STRIPPED_EUCALYPTUS_WOOD, EUCALYPTUS_PLANKS, EUCALYPTUS_STAIRS, EUCALYPTUS_SLAB, EUCALYPTUS_FENCE, EUCALYPTUS_FENCE_GATE, EUCALYPTUS_DOOR, EUCALYPTUS_TRAPDOOR, EUCALYPTUS_PRESSURE_PLATE, EUCALYPTUS_BUTTON, WoodBlocks.EUCALYPTUS_SIGN, WoodBlocks.EUCALYPTUS_HANGING_SIGN, EUCALYPTUS_LEAVES, EUCALYPTUS_SAPLING,
                BAOBAB_LOG, BAOBAB_WOOD, STRIPPED_BAOBAB_LOG, STRIPPED_BAOBAB_WOOD, BAOBAB_PLANKS, BAOBAB_STAIRS, BAOBAB_SLAB, BAOBAB_FENCE, BAOBAB_FENCE_GATE, BAOBAB_DOOR, BAOBAB_TRAPDOOR, BAOBAB_PRESSURE_PLATE, BAOBAB_BUTTON, WoodBlocks.BAOBAB_SIGN, WoodBlocks.BAOBAB_HANGING_SIGN, BAOBAB_LEAVES, BAOBAB_SAPLING,
                PALO_VERDE_LOG, PALO_VERDE_WOOD, STRIPPED_PALO_VERDE_LOG, STRIPPED_PALO_VERDE_WOOD, PALO_VERDE_PLANKS, PALO_VERDE_STAIRS, PALO_VERDE_SLAB, PALO_VERDE_FENCE, PALO_VERDE_FENCE_GATE, PALO_VERDE_DOOR, PALO_VERDE_TRAPDOOR, PALO_VERDE_PRESSURE_PLATE, PALO_VERDE_BUTTON, WoodBlocks.PALO_VERDE_SIGN, WoodBlocks.PALO_VERDE_HANGING_SIGN, PALO_VERDE_LEAVES, PALO_VERDE_SAPLING,
                JOSHUA_LOG, JOSHUA_WOOD, STRIPPED_JOSHUA_LOG, STRIPPED_JOSHUA_WOOD, JOSHUA_PLANKS, JOSHUA_STAIRS, JOSHUA_SLAB, JOSHUA_FENCE, JOSHUA_FENCE_GATE, JOSHUA_DOOR, JOSHUA_TRAPDOOR, JOSHUA_PRESSURE_PLATE, JOSHUA_BUTTON, WoodBlocks.JOSHUA_SIGN, WoodBlocks.JOSHUA_HANGING_SIGN, JOSHUA_LEAVES, JOSHUA_SAPLING,
                JUNIPER_LOG, JUNIPER_WOOD, STRIPPED_JUNIPER_LOG, STRIPPED_JUNIPER_WOOD, JUNIPER_PLANKS, JUNIPER_STAIRS, JUNIPER_SLAB, JUNIPER_FENCE, JUNIPER_FENCE_GATE, JUNIPER_DOOR, JUNIPER_TRAPDOOR, JUNIPER_PRESSURE_PLATE, JUNIPER_BUTTON, WoodBlocks.JUNIPER_SIGN, WoodBlocks.JUNIPER_HANGING_SIGN, JUNIPER_LEAVES, JUNIPER_SAPLING,
                PALM_LOG, PALM_WOOD, STRIPPED_PALM_LOG, STRIPPED_PALM_WOOD, PALM_PLANKS, PALM_STAIRS, PALM_SLAB, PALM_FENCE, PALM_FENCE_GATE, PALM_DOOR, PALM_TRAPDOOR, PALM_PRESSURE_PLATE, PALM_BUTTON, WoodBlocks.PALM_SIGN, WoodBlocks.PALM_HANGING_SIGN, PALM_LEAVES, PALM_SAPLING,
                EBONY_LOG, EBONY_WOOD, STRIPPED_EBONY_LOG, STRIPPED_EBONY_WOOD, EBONY_PLANKS, EBONY_STAIRS, EBONY_SLAB, EBONY_FENCE, EBONY_FENCE_GATE, EBONY_DOOR, EBONY_TRAPDOOR, EBONY_PRESSURE_PLATE, EBONY_BUTTON, WoodBlocks.EBONY_SIGN, WoodBlocks.EBONY_HANGING_SIGN, EBONY_LEAVES, EBONY_SAPLING,
                TEAK_LOG, TEAK_WOOD, STRIPPED_TEAK_LOG, STRIPPED_TEAK_WOOD, TEAK_PLANKS, TEAK_STAIRS, TEAK_SLAB, TEAK_FENCE, TEAK_FENCE_GATE, TEAK_DOOR, TEAK_TRAPDOOR, TEAK_PRESSURE_PLATE, TEAK_BUTTON, WoodBlocks.TEAK_SIGN, WoodBlocks.TEAK_HANGING_SIGN, TEAK_LEAVES, TEAK_SAPLING,
                ELM_LOG, ELM_WOOD, STRIPPED_ELM_LOG, STRIPPED_ELM_WOOD, ELM_PLANKS, ELM_STAIRS, ELM_SLAB, ELM_FENCE, ELM_FENCE_GATE, ELM_DOOR, ELM_TRAPDOOR, ELM_PRESSURE_PLATE, ELM_BUTTON, WoodBlocks.ELM_SIGN, WoodBlocks.ELM_HANGING_SIGN, ELM_LEAVES, ELM_SAPLING,
                WILLOW_LOG, WILLOW_WOOD, STRIPPED_WILLOW_LOG, STRIPPED_WILLOW_WOOD, WILLOW_PLANKS, WILLOW_STAIRS, WILLOW_SLAB, WILLOW_FENCE, WILLOW_FENCE_GATE, WILLOW_DOOR, WILLOW_TRAPDOOR, WILLOW_PRESSURE_PLATE, WILLOW_BUTTON, WoodBlocks.WILLOW_SIGN, WoodBlocks.WILLOW_HANGING_SIGN, WILLOW_LEAVES, WILLOW_SAPLING,
                CYPRESS_LOG, CYPRESS_WOOD, STRIPPED_CYPRESS_LOG, STRIPPED_CYPRESS_WOOD, CYPRESS_PLANKS, CYPRESS_STAIRS, CYPRESS_SLAB, CYPRESS_FENCE, CYPRESS_FENCE_GATE, CYPRESS_DOOR, CYPRESS_TRAPDOOR, CYPRESS_PRESSURE_PLATE, CYPRESS_BUTTON, WoodBlocks.CYPRESS_SIGN, WoodBlocks.CYPRESS_HANGING_SIGN, CYPRESS_LEAVES, CYPRESS_SAPLING,
                SAKURA_LOG, SAKURA_WOOD, STRIPPED_SAKURA_LOG, STRIPPED_SAKURA_WOOD, SAKURA_PLANKS, SAKURA_STAIRS, SAKURA_SLAB, SAKURA_FENCE, SAKURA_FENCE_GATE, SAKURA_DOOR, SAKURA_TRAPDOOR, SAKURA_PRESSURE_PLATE, SAKURA_BUTTON, WoodBlocks.SAKURA_SIGN, WoodBlocks.SAKURA_HANGING_SIGN, SAKURA_LEAVES, SAKURA_SAPLING,
                MAGNOLIA_LOG, MAGNOLIA_WOOD, STRIPPED_MAGNOLIA_LOG, STRIPPED_MAGNOLIA_WOOD, MAGNOLIA_PLANKS, MAGNOLIA_STAIRS, MAGNOLIA_SLAB, MAGNOLIA_FENCE, MAGNOLIA_FENCE_GATE, MAGNOLIA_DOOR, MAGNOLIA_TRAPDOOR, MAGNOLIA_PRESSURE_PLATE, MAGNOLIA_BUTTON, WoodBlocks.MAGNOLIA_SIGN, WoodBlocks.MAGNOLIA_HANGING_SIGN, MAGNOLIA_LEAVES, FLOWERING_MAGNOLIA_LEAVES, MAGNOLIA_SAPLING, FLOWERING_MAGNOLIA_SAPLING,
                JACARANDA_LOG, JACARANDA_WOOD, STRIPPED_JACARANDA_LOG, STRIPPED_JACARANDA_WOOD, JACARANDA_PLANKS, JACARANDA_STAIRS, JACARANDA_SLAB, JACARANDA_FENCE, JACARANDA_FENCE_GATE, JACARANDA_DOOR, JACARANDA_TRAPDOOR, JACARANDA_PRESSURE_PLATE, JACARANDA_BUTTON, WoodBlocks.JACARANDA_SIGN, WoodBlocks.JACARANDA_HANGING_SIGN, JACARANDA_LEAVES, JACARANDA_SAPLING,

                STONE_WALL, SMOOTH_STONE_STAIRS, SMOOTH_STONE_WALL, STONE_BRICK_PILLAR,
                POLISHED_GRANITE_WALL, GRANITE_BRICKS, CRACKED_GRANITE_BRICKS, GRANITE_BRICK_STAIRS, GRANITE_BRICK_SLAB, GRANITE_BRICK_WALL, MOSSY_GRANITE_BRICKS, MOSSY_GRANITE_BRICK_STAIRS, MOSSY_GRANITE_BRICK_SLAB, MOSSY_GRANITE_BRICK_WALL, GRANITE_BRICK_PILLAR, CHISELED_GRANITE_BRICKS, POLISHED_GRANITE_PRESSURE_PLATE, POLISHED_GRANITE_BUTTON,
                POLISHED_DIORITE_WALL, DIORITE_BRICKS, CRACKED_DIORITE_BRICKS, DIORITE_BRICK_STAIRS, DIORITE_BRICK_SLAB, DIORITE_BRICK_WALL, MOSSY_DIORITE_BRICKS, MOSSY_DIORITE_BRICK_STAIRS, MOSSY_DIORITE_BRICK_SLAB, MOSSY_DIORITE_BRICK_WALL, DIORITE_BRICK_PILLAR, CHISELED_DIORITE_BRICKS, POLISHED_DIORITE_PRESSURE_PLATE, POLISHED_DIORITE_BUTTON,
                POLISHED_ANDESITE_WALL, ANDESITE_BRICKS, CRACKED_ANDESITE_BRICKS, ANDESITE_BRICK_STAIRS, ANDESITE_BRICK_SLAB, ANDESITE_BRICK_WALL, MOSSY_ANDESITE_BRICKS, MOSSY_ANDESITE_BRICK_STAIRS, MOSSY_ANDESITE_BRICK_SLAB, MOSSY_ANDESITE_BRICK_WALL, ANDESITE_BRICK_PILLAR, CHISELED_ANDESITE_BRICKS, POLISHED_ANDESITE_PRESSURE_PLATE, POLISHED_ANDESITE_BUTTON,
                GNEISS, GNEISS_STAIRS, GNEISS_SLAB, GNEISS_WALL, POLISHED_GNEISS, POLISHED_GNEISS_STAIRS, POLISHED_GNEISS_SLAB, POLISHED_GNEISS_WALL, GNEISS_BRICKS, CRACKED_GNEISS_BRICKS, GNEISS_BRICK_STAIRS, GNEISS_BRICK_SLAB, GNEISS_BRICK_WALL, MOSSY_GNEISS_BRICKS, MOSSY_GNEISS_BRICK_STAIRS, MOSSY_GNEISS_BRICK_SLAB, MOSSY_GNEISS_BRICK_WALL, GNEISS_BRICK_PILLAR, CHISELED_GNEISS_BRICKS, POLISHED_GNEISS_PRESSURE_PLATE, POLISHED_GNEISS_BUTTON,
                SHALE, SHALE_STAIRS, SHALE_SLAB, SHALE_WALL, POLISHED_SHALE, POLISHED_SHALE_STAIRS, POLISHED_SHALE_SLAB, POLISHED_SHALE_WALL, SHALE_BRICKS, CRACKED_SHALE_BRICKS, SHALE_BRICK_STAIRS, SHALE_BRICK_SLAB, SHALE_BRICK_WALL, MOSSY_SHALE_BRICKS, MOSSY_SHALE_BRICK_STAIRS, MOSSY_SHALE_BRICK_SLAB, MOSSY_SHALE_BRICK_WALL, SHALE_BRICK_PILLAR, CHISELED_SHALE_BRICKS, POLISHED_SHALE_PRESSURE_PLATE, POLISHED_SHALE_BUTTON,
                LIMESTONE, LIMESTONE_STAIRS, LIMESTONE_SLAB, LIMESTONE_WALL, POLISHED_LIMESTONE, POLISHED_LIMESTONE_STAIRS, POLISHED_LIMESTONE_SLAB, POLISHED_LIMESTONE_WALL, LIMESTONE_BRICKS, CRACKED_LIMESTONE_BRICKS, LIMESTONE_BRICK_STAIRS, LIMESTONE_BRICK_SLAB, LIMESTONE_BRICK_WALL, MOSSY_LIMESTONE_BRICKS, MOSSY_LIMESTONE_BRICK_STAIRS, MOSSY_LIMESTONE_BRICK_SLAB, MOSSY_LIMESTONE_BRICK_WALL, LIMESTONE_BRICK_PILLAR, CHISELED_LIMESTONE_BRICKS, POLISHED_LIMESTONE_PRESSURE_PLATE, POLISHED_LIMESTONE_BUTTON,
                MARBLE, MARBLE_STAIRS, MARBLE_SLAB, MARBLE_WALL, POLISHED_MARBLE, POLISHED_MARBLE_STAIRS, POLISHED_MARBLE_SLAB, POLISHED_MARBLE_WALL, MARBLE_BRICKS, CRACKED_MARBLE_BRICKS, MARBLE_BRICK_STAIRS, MARBLE_BRICK_SLAB, MARBLE_BRICK_WALL, MOSSY_MARBLE_BRICKS, MOSSY_MARBLE_BRICK_STAIRS, MOSSY_MARBLE_BRICK_SLAB, MOSSY_MARBLE_BRICK_WALL, MARBLE_BRICK_PILLAR, CHISELED_MARBLE_BRICKS, POLISHED_MARBLE_PRESSURE_PLATE, POLISHED_MARBLE_BUTTON,
                GABBRO, GABBRO_STAIRS, GABBRO_SLAB, GABBRO_WALL, POLISHED_GABBRO, POLISHED_GABBRO_STAIRS, POLISHED_GABBRO_SLAB, POLISHED_GABBRO_WALL, GABBRO_BRICKS, CRACKED_GABBRO_BRICKS, GABBRO_BRICK_STAIRS, GABBRO_BRICK_SLAB, GABBRO_BRICK_WALL, MOSSY_GABBRO_BRICKS, MOSSY_GABBRO_BRICK_STAIRS, MOSSY_GABBRO_BRICK_SLAB, MOSSY_GABBRO_BRICK_WALL, GABBRO_BRICK_PILLAR, CHISELED_GABBRO_BRICKS, POLISHED_GABBRO_PRESSURE_PLATE, POLISHED_GABBRO_BUTTON,
                PHYLLITE, PHYLLITE_STAIRS, PHYLLITE_SLAB, PHYLLITE_WALL, POLISHED_PHYLLITE, POLISHED_PHYLLITE_STAIRS, POLISHED_PHYLLITE_SLAB, POLISHED_PHYLLITE_WALL, PHYLLITE_BRICKS, CRACKED_PHYLLITE_BRICKS, PHYLLITE_BRICK_STAIRS, PHYLLITE_BRICK_SLAB, PHYLLITE_BRICK_WALL, MOSSY_PHYLLITE_BRICKS, MOSSY_PHYLLITE_BRICK_STAIRS, MOSSY_PHYLLITE_BRICK_SLAB, MOSSY_PHYLLITE_BRICK_WALL, PHYLLITE_BRICK_PILLAR, CHISELED_PHYLLITE_BRICKS, POLISHED_PHYLLITE_PRESSURE_PLATE, POLISHED_PHYLLITE_BUTTON,
                CRACKED_TUFF_BRICKS,
                CALCITE_STAIRS, CALCITE_SLAB, CALCITE_WALL, POLISHED_CALCITE, POLISHED_CALCITE_STAIRS, POLISHED_CALCITE_SLAB, POLISHED_CALCITE_WALL, CALCITE_BRICKS, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_STAIRS, CALCITE_BRICK_SLAB, CALCITE_BRICK_WALL, CHISELED_CALCITE,
                DRIPSTONE_STAIRS, DRIPSTONE_SLAB, DRIPSTONE_WALL, POLISHED_DRIPSTONE, POLISHED_DRIPSTONE_STAIRS, POLISHED_DRIPSTONE_SLAB, POLISHED_DRIPSTONE_WALL, DRIPSTONE_BRICKS, CRACKED_DRIPSTONE_BRICKS, DRIPSTONE_BRICK_STAIRS, DRIPSTONE_BRICK_SLAB, DRIPSTONE_BRICK_WALL, CHISELED_DRIPSTONE,
                CRACKED_BRICKS, CRACKED_MUD_BRICKS, CHISELED_MUD_BRICKS,
                CUT_SANDSTONE_STAIRS, CUT_SANDSTONE_WALL, SMOOTH_SANDSTONE_WALL, ROUGH_SANDSTONE, ROUGH_SANDSTONE_STAIRS, ROUGH_SANDSTONE_SLAB, ROUGH_SANDSTONE_WALL, CUT_RED_SANDSTONE_STAIRS, CUT_RED_SANDSTONE_WALL, SMOOTH_RED_SANDSTONE_WALL, ROUGH_RED_SANDSTONE, ROUGH_RED_SANDSTONE_STAIRS, ROUGH_RED_SANDSTONE_SLAB, ROUGH_RED_SANDSTONE_WALL,
                FROSTED_SAND, FROSTED_SANDSTONE, FROSTED_SANDSTONE_STAIRS, FROSTED_SANDSTONE_SLAB, FROSTED_SANDSTONE_WALL, CHISELED_FROSTED_SANDSTONE, CUT_FROSTED_SANDSTONE, CUT_FROSTED_SANDSTONE_STAIRS, CUT_FROSTED_SANDSTONE_SLAB, CUT_FROSTED_SANDSTONE_WALL, SMOOTH_FROSTED_SANDSTONE, SMOOTH_FROSTED_SANDSTONE_STAIRS, SMOOTH_FROSTED_SANDSTONE_SLAB, SMOOTH_FROSTED_SANDSTONE_WALL, ROUGH_FROSTED_SANDSTONE, ROUGH_FROSTED_SANDSTONE_STAIRS, ROUGH_FROSTED_SANDSTONE_SLAB, ROUGH_FROSTED_SANDSTONE_WALL,
                CHARRED_SAND, CHARRED_SANDSTONE, CHARRED_SANDSTONE_STAIRS, CHARRED_SANDSTONE_SLAB, CHARRED_SANDSTONE_WALL, CHISELED_CHARRED_SANDSTONE, CUT_CHARRED_SANDSTONE, CUT_CHARRED_SANDSTONE_STAIRS, CUT_CHARRED_SANDSTONE_SLAB, CUT_CHARRED_SANDSTONE_WALL, SMOOTH_CHARRED_SANDSTONE, SMOOTH_CHARRED_SANDSTONE_STAIRS, SMOOTH_CHARRED_SANDSTONE_SLAB, SMOOTH_CHARRED_SANDSTONE_WALL, ROUGH_CHARRED_SANDSTONE, ROUGH_CHARRED_SANDSTONE_STAIRS, ROUGH_CHARRED_SANDSTONE_SLAB, ROUGH_CHARRED_SANDSTONE_WALL,
                CRACKED_PRISMARINE_BRICKS, PRISMARINE_BRICK_WALL, DARK_PRISMARINE_WALL, CHISELED_PRISMARINE_BRICKS,
                CRACKED_RED_NETHER_BRICKS, RED_NETHER_BRICK_FENCE, CHISELED_RED_NETHER_BRICKS, BLUE_NETHER_BRICKS, CRACKED_BLUE_NETHER_BRICKS, BLUE_NETHER_BRICK_STAIRS, BLUE_NETHER_BRICK_SLAB, BLUE_NETHER_BRICK_WALL, BLUE_NETHER_BRICK_FENCE, CHISELED_BLUE_NETHER_BRICKS,
                QUARTZ_WALL, CRACKED_QUARTZ_BRICKS, QUARTZ_BRICK_STAIRS, QUARTZ_BRICK_SLAB, QUARTZ_BRICK_WALL, SMOOTH_QUARTZ_WALL,
                AMETHYST_STAIRS, AMETHYST_SLAB, AMETHYST_WALL, AMETHYST_BRICKS, CRACKED_AMETHYST_BRICKS, AMETHYST_BRICK_STAIRS, AMETHYST_BRICK_SLAB, AMETHYST_BRICK_WALL, AMETHYST_TILES, CRACKED_AMETHYST_TILES, AMETHYST_TILE_STAIRS, AMETHYST_TILE_SLAB, AMETHYST_TILE_WALL, CHISELED_AMETHYST,
                DOLOMITE, DOLOMITE_STAIRS, DOLOMITE_SLAB, DOLOMITE_WALL, DOLOMITE_BRICKS, CRACKED_DOLOMITE_BRICKS, DOLOMITE_BRICK_STAIRS, DOLOMITE_BRICK_SLAB, DOLOMITE_BRICK_WALL, DOLOMITE_TILES, CRACKED_DOLOMITE_TILES, DOLOMITE_TILE_STAIRS, DOLOMITE_TILE_SLAB, DOLOMITE_TILE_WALL, CHISELED_DOLOMITE,
                GYPSUM, GYPSUM_STAIRS, GYPSUM_SLAB, GYPSUM_WALL, GYPSUM_BRICKS, CRACKED_GYPSUM_BRICKS, GYPSUM_BRICK_STAIRS, GYPSUM_BRICK_SLAB, GYPSUM_BRICK_WALL, GYPSUM_TILES, CRACKED_GYPSUM_TILES, GYPSUM_TILE_STAIRS, GYPSUM_TILE_SLAB, GYPSUM_TILE_WALL, CHISELED_GYPSUM,

                WHITE_CONCRETE_STAIRS, WHITE_CONCRETE_SLAB, WHITE_CONCRETE_WALL, LIGHT_GRAY_CONCRETE_STAIRS, LIGHT_GRAY_CONCRETE_SLAB, LIGHT_GRAY_CONCRETE_WALL, GRAY_CONCRETE_STAIRS, GRAY_CONCRETE_SLAB, GRAY_CONCRETE_WALL, BLACK_CONCRETE_STAIRS, BLACK_CONCRETE_SLAB, BLACK_CONCRETE_WALL,
                BROWN_CONCRETE_STAIRS, BROWN_CONCRETE_SLAB, BROWN_CONCRETE_WALL, RED_CONCRETE_STAIRS, RED_CONCRETE_SLAB, RED_CONCRETE_WALL, ORANGE_CONCRETE_STAIRS, ORANGE_CONCRETE_SLAB, ORANGE_CONCRETE_WALL, YELLOW_CONCRETE_STAIRS, YELLOW_CONCRETE_SLAB, YELLOW_CONCRETE_WALL,
                LIME_CONCRETE_STAIRS, LIME_CONCRETE_SLAB, LIME_CONCRETE_WALL, GREEN_CONCRETE_STAIRS, GREEN_CONCRETE_SLAB, GREEN_CONCRETE_WALL, CYAN_CONCRETE_STAIRS, CYAN_CONCRETE_SLAB, CYAN_CONCRETE_WALL, LIGHT_BLUE_CONCRETE_STAIRS, LIGHT_BLUE_CONCRETE_SLAB, LIGHT_BLUE_CONCRETE_WALL,
                BLUE_CONCRETE_STAIRS, BLUE_CONCRETE_SLAB, BLUE_CONCRETE_WALL, PURPLE_CONCRETE_STAIRS, PURPLE_CONCRETE_SLAB, PURPLE_CONCRETE_WALL, MAGENTA_CONCRETE_STAIRS, MAGENTA_CONCRETE_SLAB, MAGENTA_CONCRETE_WALL, PINK_CONCRETE_STAIRS, PINK_CONCRETE_SLAB, PINK_CONCRETE_WALL,
                TERRACOTTA_STAIRS, TERRACOTTA_SLAB, TERRACOTTA_WALL, WHITE_TERRACOTTA_STAIRS, WHITE_TERRACOTTA_SLAB, WHITE_TERRACOTTA_WALL, LIGHT_GRAY_TERRACOTTA_STAIRS, LIGHT_GRAY_TERRACOTTA_SLAB, LIGHT_GRAY_TERRACOTTA_WALL, GRAY_TERRACOTTA_STAIRS, GRAY_TERRACOTTA_SLAB, GRAY_TERRACOTTA_WALL, BLACK_TERRACOTTA_STAIRS, BLACK_TERRACOTTA_SLAB, BLACK_TERRACOTTA_WALL,
                BROWN_TERRACOTTA_STAIRS, BROWN_TERRACOTTA_SLAB, BROWN_TERRACOTTA_WALL, RED_TERRACOTTA_STAIRS, RED_TERRACOTTA_SLAB, RED_TERRACOTTA_WALL, ORANGE_TERRACOTTA_STAIRS, ORANGE_TERRACOTTA_SLAB, ORANGE_TERRACOTTA_WALL, YELLOW_TERRACOTTA_STAIRS, YELLOW_TERRACOTTA_SLAB, YELLOW_TERRACOTTA_WALL,
                LIME_TERRACOTTA_STAIRS, LIME_TERRACOTTA_SLAB, LIME_TERRACOTTA_WALL, GREEN_TERRACOTTA_STAIRS, GREEN_TERRACOTTA_SLAB, GREEN_TERRACOTTA_WALL, CYAN_TERRACOTTA_STAIRS, CYAN_TERRACOTTA_SLAB, CYAN_TERRACOTTA_WALL, LIGHT_BLUE_TERRACOTTA_STAIRS, LIGHT_BLUE_TERRACOTTA_SLAB, LIGHT_BLUE_TERRACOTTA_WALL,
                BLUE_TERRACOTTA_STAIRS, BLUE_TERRACOTTA_SLAB, BLUE_TERRACOTTA_WALL, PURPLE_TERRACOTTA_STAIRS, PURPLE_TERRACOTTA_SLAB, PURPLE_TERRACOTTA_WALL, MAGENTA_TERRACOTTA_STAIRS, MAGENTA_TERRACOTTA_SLAB, MAGENTA_TERRACOTTA_WALL, PINK_TERRACOTTA_STAIRS, PINK_TERRACOTTA_SLAB, PINK_TERRACOTTA_WALL,
                TERRACOTTA_BRICKS, TERRACOTTA_BRICK_STAIRS, TERRACOTTA_BRICK_SLAB, TERRACOTTA_BRICK_WALL, WHITE_TERRACOTTA_BRICKS, WHITE_TERRACOTTA_BRICK_STAIRS, WHITE_TERRACOTTA_BRICK_SLAB, WHITE_TERRACOTTA_BRICK_WALL, LIGHT_GRAY_TERRACOTTA_BRICKS, LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS, LIGHT_GRAY_TERRACOTTA_BRICK_SLAB, LIGHT_GRAY_TERRACOTTA_BRICK_WALL, GRAY_TERRACOTTA_BRICKS, GRAY_TERRACOTTA_BRICK_STAIRS, GRAY_TERRACOTTA_BRICK_SLAB, GRAY_TERRACOTTA_BRICK_WALL, BLACK_TERRACOTTA_BRICKS, BLACK_TERRACOTTA_BRICK_STAIRS, BLACK_TERRACOTTA_BRICK_SLAB, BLACK_TERRACOTTA_BRICK_WALL,
                BROWN_TERRACOTTA_BRICKS, BROWN_TERRACOTTA_BRICK_STAIRS, BROWN_TERRACOTTA_BRICK_SLAB, BROWN_TERRACOTTA_BRICK_WALL, RED_TERRACOTTA_BRICKS, RED_TERRACOTTA_BRICK_STAIRS, RED_TERRACOTTA_BRICK_SLAB, RED_TERRACOTTA_BRICK_WALL, ORANGE_TERRACOTTA_BRICKS, ORANGE_TERRACOTTA_BRICK_STAIRS, ORANGE_TERRACOTTA_BRICK_SLAB, ORANGE_TERRACOTTA_BRICK_WALL, YELLOW_TERRACOTTA_BRICKS, YELLOW_TERRACOTTA_BRICK_STAIRS, YELLOW_TERRACOTTA_BRICK_SLAB, YELLOW_TERRACOTTA_BRICK_WALL,
                LIME_TERRACOTTA_BRICKS, LIME_TERRACOTTA_BRICK_STAIRS, LIME_TERRACOTTA_BRICK_SLAB, LIME_TERRACOTTA_BRICK_WALL, GREEN_TERRACOTTA_BRICKS, GREEN_TERRACOTTA_BRICK_STAIRS, GREEN_TERRACOTTA_BRICK_SLAB, GREEN_TERRACOTTA_BRICK_WALL, CYAN_TERRACOTTA_BRICKS, CYAN_TERRACOTTA_BRICK_STAIRS, CYAN_TERRACOTTA_BRICK_SLAB, CYAN_TERRACOTTA_BRICK_WALL, LIGHT_BLUE_TERRACOTTA_BRICKS, LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS, LIGHT_BLUE_TERRACOTTA_BRICK_SLAB, LIGHT_BLUE_TERRACOTTA_BRICK_WALL,
                BLUE_TERRACOTTA_BRICKS, BLUE_TERRACOTTA_BRICK_STAIRS, BLUE_TERRACOTTA_BRICK_SLAB, BLUE_TERRACOTTA_BRICK_WALL, PURPLE_TERRACOTTA_BRICKS, PURPLE_TERRACOTTA_BRICK_STAIRS, PURPLE_TERRACOTTA_BRICK_SLAB, PURPLE_TERRACOTTA_BRICK_WALL, MAGENTA_TERRACOTTA_BRICKS, MAGENTA_TERRACOTTA_BRICK_STAIRS, MAGENTA_TERRACOTTA_BRICK_SLAB, MAGENTA_TERRACOTTA_BRICK_WALL, PINK_TERRACOTTA_BRICKS, PINK_TERRACOTTA_BRICK_STAIRS, PINK_TERRACOTTA_BRICK_SLAB, PINK_TERRACOTTA_BRICK_WALL,
                CHALK, CHALK_STAIRS, CHALK_SLAB, CHALK_WALL, WHITE_CHALK, WHITE_CHALK_STAIRS, WHITE_CHALK_SLAB, WHITE_CHALK_WALL, LIGHT_GRAY_CHALK, LIGHT_GRAY_CHALK_STAIRS, LIGHT_GRAY_CHALK_SLAB, LIGHT_GRAY_CHALK_WALL, GRAY_CHALK, GRAY_CHALK_STAIRS, GRAY_CHALK_SLAB, GRAY_CHALK_WALL, BLACK_CHALK, BLACK_CHALK_SLAB, BLACK_CHALK_WALL,
                BROWN_CHALK, BROWN_CHALK_STAIRS, BROWN_CHALK_SLAB, BROWN_CHALK_WALL, RED_CHALK, RED_CHALK_STAIRS, RED_CHALK_SLAB, RED_CHALK_WALL, ORANGE_CHALK, ORANGE_CHALK_STAIRS, ORANGE_CHALK_SLAB, ORANGE_CHALK_WALL, YELLOW_CHALK, YELLOW_CHALK_SLAB, YELLOW_CHALK_WALL,
                LIME_CHALK, LIME_CHALK_STAIRS, LIME_CHALK_SLAB, LIME_CHALK_WALL, GREEN_CHALK, GREEN_CHALK_SLAB, GREEN_CHALK_WALL, CYAN_CHALK, CYAN_CHALK_SLAB, CYAN_CHALK_WALL, LIGHT_BLUE_CHALK, LIGHT_BLUE_CHALK_SLAB, LIGHT_BLUE_CHALK_WALL,
                BLUE_CHALK, BLUE_CHALK_SLAB, BLUE_CHALK_WALL, PURPLE_CHALK, PURPLE_CHALK_SLAB, PURPLE_CHALK_WALL, MAGENTA_CHALK, MAGENTA_CHALK_SLAB, MAGENTA_CHALK_WALL, PINK_CHALK, PINK_CHALK_SLAB, PINK_CHALK_WALL,
                CHALK_BRICKS, CHALK_BRICK_STAIRS, CHALK_BRICK_SLAB, CHALK_BRICK_WALL, WHITE_CHALK_BRICKS, WHITE_CHALK_BRICK_STAIRS, WHITE_CHALK_BRICK_SLAB, WHITE_CHALK_BRICK_WALL, LIGHT_GRAY_CHALK_BRICKS, LIGHT_GRAY_CHALK_BRICK_STAIRS, LIGHT_GRAY_CHALK_BRICK_SLAB, LIGHT_GRAY_CHALK_BRICK_WALL, GRAY_CHALK_BRICKS, GRAY_CHALK_BRICK_STAIRS, GRAY_CHALK_BRICK_SLAB, GRAY_CHALK_BRICK_WALL, BLACK_CHALK_BRICKS, BLACK_CHALK_BRICK_STAIRS, BLACK_CHALK_BRICK_SLAB, BLACK_CHALK_BRICK_WALL,
                BROWN_CHALK_BRICKS, BROWN_CHALK_BRICK_STAIRS, BROWN_CHALK_BRICK_SLAB, BROWN_CHALK_BRICK_WALL, RED_CHALK_BRICKS, RED_CHALK_BRICK_STAIRS, RED_CHALK_BRICK_SLAB, RED_CHALK_BRICK_WALL, ORANGE_CHALK_BRICKS, ORANGE_CHALK_BRICK_STAIRS, ORANGE_CHALK_BRICK_SLAB, ORANGE_CHALK_BRICK_WALL, YELLOW_CHALK_BRICKS, YELLOW_CHALK_BRICK_STAIRS, YELLOW_CHALK_BRICK_SLAB, YELLOW_CHALK_BRICK_WALL,
                LIME_CHALK_BRICKS, LIME_CHALK_BRICK_STAIRS, LIME_CHALK_BRICK_SLAB, LIME_CHALK_BRICK_WALL, GREEN_CHALK_BRICKS, GREEN_CHALK_BRICK_STAIRS, GREEN_CHALK_BRICK_SLAB, GREEN_CHALK_BRICK_WALL, CYAN_CHALK_BRICKS, CYAN_CHALK_BRICK_STAIRS, CYAN_CHALK_BRICK_SLAB, CYAN_CHALK_BRICK_WALL, LIGHT_BLUE_CHALK_BRICKS, LIGHT_BLUE_CHALK_BRICK_STAIRS, LIGHT_BLUE_CHALK_BRICK_SLAB, LIGHT_BLUE_CHALK_BRICK_WALL,
                BLUE_CHALK_BRICKS, BLUE_CHALK_BRICK_STAIRS, BLUE_CHALK_BRICK_SLAB, BLUE_CHALK_BRICK_WALL, PURPLE_CHALK_BRICKS, PURPLE_CHALK_BRICK_STAIRS, PURPLE_CHALK_BRICK_SLAB, PURPLE_CHALK_BRICK_WALL, MAGENTA_CHALK_BRICKS, MAGENTA_CHALK_BRICK_STAIRS, MAGENTA_CHALK_BRICK_SLAB, MAGENTA_CHALK_BRICK_WALL, PINK_CHALK_BRICKS, PINK_CHALK_BRICK_STAIRS, PINK_CHALK_BRICK_SLAB, PINK_CHALK_BRICK_WALL,

                SHORT_PRAIRIE_GRASS, TALL_PRAIRIE_GRASS, CATTAIL, PEAT_BLOCK, PEAT, GOURD, CARVED_GOURD, LAVENDER, PURPLE_PETALS, HANGING_MOSS,
                ARTICHOKES, BROCCOLI, CABBAGE, CANTALOUPE, CAULIFLOWER, CELERY, CUCUMBERS, EGGPLANT, KALE, LETTUCE, ONIONS, RADISHES, SPINACH
        };

        for (Block block : allBlocks) {
            translationBuilder.add(block, format(block.getTranslationKey()));
        }

        Item[] simpleItems = {
                WARPED_WART, GOURD_SEEDS,
                APRICOT, KIWI, NECTARINE, PEACH, PEAR, PLUM, KUMQUAT, OLIVE, PERSIMMON, POMEGRANATE, CHERRY, FIG, GRAPEFRUIT, GUAVA, TANGERINE, AVOCADO, BANANA, LEMON, LIME, MANGO, ORANGE, STARFRUIT,
                BlockItems.ARTICHOKE, BlockItems.BROCCOLI, BlockItems.CABBAGE, BlockItems.CANTALOUPE, BlockItems.CAULIFLOWER, BlockItems.CELERY, BlockItems.CUCUMBER, BlockItems.EGGPLANT, BlockItems.KALE, BlockItems.LETTUCE, BlockItems.ONION, BlockItems.RADISH, BlockItems.SPINACH
        };

        for (Item item : simpleItems) {
            translationBuilder.add(item, format(item.getTranslationKey()));
        }

        Item[] shortItems = {
                BlockItems.GRANITE_COAL_ORE, BlockItems.DIORITE_COAL_ORE, BlockItems.ANDESITE_COAL_ORE, BlockItems.TUFF_COAL_ORE, BlockItems.GNEISS_COAL_ORE, BlockItems.SHALE_COAL_ORE, BlockItems.LIMESTONE_COAL_ORE, BlockItems.MARBLE_COAL_ORE, BlockItems.GABBRO_COAL_ORE, BlockItems.PHYLLITE_COAL_ORE,
                BlockItems.GRANITE_IRON_ORE, BlockItems.DIORITE_IRON_ORE, BlockItems.ANDESITE_IRON_ORE, BlockItems.TUFF_IRON_ORE, BlockItems.GNEISS_IRON_ORE, BlockItems.SHALE_IRON_ORE, BlockItems.LIMESTONE_IRON_ORE, BlockItems.MARBLE_IRON_ORE, BlockItems.GABBRO_IRON_ORE, BlockItems.PHYLLITE_IRON_ORE,
                BlockItems.GRANITE_COPPER_ORE, BlockItems.DIORITE_COPPER_ORE, BlockItems.ANDESITE_COPPER_ORE, BlockItems.TUFF_COPPER_ORE, BlockItems.GNEISS_COPPER_ORE, BlockItems.SHALE_COPPER_ORE, BlockItems.LIMESTONE_COPPER_ORE, BlockItems.MARBLE_COPPER_ORE, BlockItems.GABBRO_COPPER_ORE, BlockItems.PHYLLITE_COPPER_ORE,
                BlockItems.GRANITE_GOLD_ORE, BlockItems.DIORITE_GOLD_ORE, BlockItems.ANDESITE_GOLD_ORE, BlockItems.TUFF_GOLD_ORE, BlockItems.GNEISS_GOLD_ORE, BlockItems.SHALE_GOLD_ORE, BlockItems.LIMESTONE_GOLD_ORE, BlockItems.MARBLE_GOLD_ORE, BlockItems.GABBRO_GOLD_ORE, BlockItems.PHYLLITE_GOLD_ORE,
                BlockItems.GRANITE_REDSTONE_ORE, BlockItems.DIORITE_REDSTONE_ORE, BlockItems.ANDESITE_REDSTONE_ORE, BlockItems.TUFF_REDSTONE_ORE, BlockItems.GNEISS_REDSTONE_ORE, BlockItems.SHALE_REDSTONE_ORE, BlockItems.LIMESTONE_REDSTONE_ORE, BlockItems.MARBLE_REDSTONE_ORE, BlockItems.GABBRO_REDSTONE_ORE, BlockItems.PHYLLITE_REDSTONE_ORE,
                BlockItems.GRANITE_EMERALD_ORE, BlockItems.DIORITE_EMERALD_ORE, BlockItems.ANDESITE_EMERALD_ORE, BlockItems.TUFF_EMERALD_ORE, BlockItems.GNEISS_EMERALD_ORE, BlockItems.SHALE_EMERALD_ORE, BlockItems.LIMESTONE_EMERALD_ORE, BlockItems.MARBLE_EMERALD_ORE, BlockItems.GABBRO_EMERALD_ORE, BlockItems.PHYLLITE_EMERALD_ORE,
                BlockItems.GRANITE_LAPIS_ORE, BlockItems.DIORITE_LAPIS_ORE, BlockItems.ANDESITE_LAPIS_ORE, BlockItems.TUFF_LAPIS_ORE, BlockItems.GNEISS_LAPIS_ORE, BlockItems.SHALE_LAPIS_ORE, BlockItems.LIMESTONE_LAPIS_ORE, BlockItems.MARBLE_LAPIS_ORE, BlockItems.GABBRO_LAPIS_ORE, BlockItems.PHYLLITE_LAPIS_ORE,
                BlockItems.GRANITE_DIAMOND_ORE, BlockItems.DIORITE_DIAMOND_ORE, BlockItems.ANDESITE_DIAMOND_ORE, BlockItems.TUFF_DIAMOND_ORE, BlockItems.GNEISS_DIAMOND_ORE, BlockItems.SHALE_DIAMOND_ORE, BlockItems.LIMESTONE_DIAMOND_ORE, BlockItems.MARBLE_DIAMOND_ORE, BlockItems.GABBRO_DIAMOND_ORE, BlockItems.PHYLLITE_DIAMOND_ORE,

                RUNE_AQUA_AFFINITY, RUNE_BANE_OF_ARTHROPODS, RUNE_BLAST_PROTECTION, RUNE_BREACH, RUNE_CHANNELING, RUNE_DENSITY, RUNE_DEPTH_STRIDER, RUNE_EFFICIENCY, RUNE_FEATHER_FALLING, RUNE_FIRE_ASPECT,
                RUNE_FIRE_PROTECTION, RUNE_FLAME, RUNE_FORTUNE, RUNE_FROST_WALKER, RUNE_IMPALING, RUNE_INFINITY, RUNE_KNOCKBACK, RUNE_LOOTING, RUNE_LOYALTY, RUNE_LUCK_OF_THE_SEA,
                RUNE_LURE, RUNE_MENDING, RUNE_MULTISHOT, RUNE_PIERCING, RUNE_POWER, RUNE_PROJECTILE_PROTECTION, RUNE_PROTECTION, RUNE_PUNCH, RUNE_QUICK_CHARGE, RUNE_RESPIRATION,
                RUNE_RIPTIDE, RUNE_SHARPNESS, RUNE_SILK_TOUCH, RUNE_SMITE, RUNE_SOUL_SPEED, RUNE_SWEEPING_EDGE, RUNE_SWIFT_SNEAK, RUNE_THORNS, RUNE_UNBREAKING, RUNE_WIND_BURST
        };

        for (Item shortItem : shortItems) {
            translationBuilder.add(shortItem, shortFormat(shortItem.getTranslationKey()));
        }

        translationBuilder.add(JALAPENOS, "Jalapeños");
        translationBuilder.add(BlockItems.JALAPENO, "Jalapeño");

        translationBuilder.add(TOOLTIP_PATH + "ore_granite", "Granite");
        translationBuilder.add(TOOLTIP_PATH + "ore_diorite", "Diorite");
        translationBuilder.add(TOOLTIP_PATH + "ore_andesite", "Andesite");
        translationBuilder.add(TOOLTIP_PATH + "ore_tuff", "Tuff");
        translationBuilder.add(TOOLTIP_PATH + "ore_gneiss", "Gneiss");
        translationBuilder.add(TOOLTIP_PATH + "ore_shale", "Shale");
        translationBuilder.add(TOOLTIP_PATH + "ore_limestone", "Limestone");
        translationBuilder.add(TOOLTIP_PATH + "ore_marble", "Marble");
        translationBuilder.add(TOOLTIP_PATH + "ore_gabbro", "Gabbro");
        translationBuilder.add(TOOLTIP_PATH + "ore_phyllite", "Phyllite");
        translationBuilder.add(TOOLTIP_PATH + "rune", "Enchantment Rune");

        translationBuilder.add(WITHERS_OVERHAUL_BLOCKS_KEY, "Wither's Overhaul - Blocks");
        translationBuilder.add(WITHERS_OVERHAUL_ITEMS_KEY, "Wither's Overhaul - Items");

        List<RegistryKey<Biome>> biomes = List.of(
                ALPINE_FOREST, ALPINE_PEAKS, ALPINE_TANGLE, ASHEN_FIELDS, ASPEN_GROVE,
                BAYOU, BOG, BURIED_DUNES, CHARCOAL_SHORE, CLOUD_FOREST, COLD_RIVER,
                COOL_OCEAN, COOL_RIVER, CRYSTAL_CAVES, DEEP_COOL_OCEAN, DEEP_WARM_OCEAN,
                DESERT_FIELDS, ECHOING_HOLLOW, ENCHANTED_FOREST, FORGOTTEN_ISLES, FOSSILIZED_DEPTHS,
                FROSTBURN_CAVES, FROSTED_TANGLE, FROSTED_WOODLANDS, FROZEN_WETLANDS, FUNGAL_CHASM,
                GLACIAL_SWEEP, GLOWING_GROTTO, GOLDEN_SWEEP, LAVENDER_FIELDS, LUKEWARM_RIVER,
                LUSH_RIVER, MARSH, MOLTEN_UNDERGROWTH, MONSOON_RAINFOREST, MONTANE_CLEARING,
                MONTANE_WOODLANDS, MUTED_TUNNELS, OASIS, OLD_GROWTH_SNOWY_TAIGA, PAINTED_BEACH,
                PAINTED_PEAKS, PALE_UNDERGROWTH, PASTEL_CAVERNS, PHANTOM_HOLLOW, PINE_TAIGA,
                PRAIRIE, RAINBOW_FIELDS, REDWOOD_FOREST, SALT_MARSH, SALT_RIVER, SANDY_RIVER,
                SHIMMERING_WASTELANDS, SHRUBLANDS, SPECTRAL_ABYSS, STEPPE, SUBZERO_ABYSS,
                SUNBAKED_PEAKS, SUNBAKED_SHORE, TANGLED_TROPICS, TOXIC_WASTES, TROPICAL_BEACH,
                TROPICAL_RAINFOREST, TUNDRA, VOLCANIC_PEAKS, WHIMSY, WINDSWEPT_TUNDRA, WINTER_WONDERLAND
        );

        for (RegistryKey<Biome> biome : biomes) {
            translationBuilder.add("biome.withers_overhaul." + biome.getValue().getPath(), format(biome.getValue().getPath()));
        }

        translationBuilder.add("biome.withers_overhaul.crystal_caves_frozen", "Crystal Caves (Frozen)");
        translationBuilder.add("biome.withers_overhaul.crystal_caves_cold", "Crystal Caves (Cold)");
        translationBuilder.add("biome.withers_overhaul.crystal_caves_cool", "Crystal Caves (Cool)");
        translationBuilder.add("biome.withers_overhaul.crystal_caves_lukewarm", "Crystal Caves (Lukewarm)");
        translationBuilder.add("biome.withers_overhaul.crystal_caves_warm", "Crystal Caves (Warm)");
    }

    String format(String input) {
        String [] words = split(input);

        for (int i = 0; i < words.length; i++) {
            words[i] = words[i].substring(0, 1).toUpperCase() + words[i].substring(1).toLowerCase();
        }

        return String.join(" ", words);
    }

    String shortFormat(String input) {
        String[] words = split(input);

        for (int i = 1; i < words.length; i++) {
            words[i] = words[i].substring(0, 1).toUpperCase() + words[i].substring(1).toLowerCase();
        }

        return String.join(" ", Arrays.copyOfRange(words, 1, words.length));
    }

    String[] split(String input) {
        // Split by dots and take the last part
        String lastPart = input.substring(input.lastIndexOf('.') + 1);

        // Split by underscores, capitalize each word, and join with spaces
        return lastPart.split("_");
    }
}
