package me.withers_overhaul.world.biome;

import me.withers_overhaul.WithersOverhaul;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.Identifier;
import net.minecraft.world.biome.Biome;

public class OverhaulBiomeKeys {

    public static final RegistryKey<Biome> ALPINE_FOREST = keyOf("alpine_forest");
    public static final RegistryKey<Biome> ALPINE_PEAKS = keyOf("alpine_peaks");
    public static final RegistryKey<Biome> ALPINE_TANGLE = keyOf("alpine_tangle");
    public static final RegistryKey<Biome> ALPINE_THICKET = keyOf("alpine_thicket");
    public static final RegistryKey<Biome> ASHEN_FIELDS = keyOf("ashen_fields");
    public static final RegistryKey<Biome> ASPEN_GROVE = keyOf("aspen_grove");
    public static final RegistryKey<Biome> BAYOU = keyOf("bayou");
    public static final RegistryKey<Biome> BOG = keyOf("bog");
    public static final RegistryKey<Biome> BURIED_DUNES = keyOf("buried_dunes");
    public static final RegistryKey<Biome> CHARCOAL_SHORE = keyOf("charcoal_shore");
    public static final RegistryKey<Biome> CLOUD_FOREST = keyOf("cloud_forest");
    public static final RegistryKey<Biome> COLD_RIVER = keyOf("cold_river");
    public static final RegistryKey<Biome> COOL_OCEAN = keyOf("cool_ocean");
    public static final RegistryKey<Biome> COOL_RIVER = keyOf("cool_river");
    public static final RegistryKey<Biome> CRYSTAL_CAVES = keyOf("crystal_caves");
    public static final RegistryKey<Biome> CRYSTAL_CAVES_COLD = keyOf("crystal_caves_cold");
    public static final RegistryKey<Biome> CRYSTAL_CAVES_COOL = keyOf("crystal_caves_cool");
    public static final RegistryKey<Biome> CRYSTAL_CAVES_FROZEN = keyOf("crystal_caves_frozen");
    public static final RegistryKey<Biome> CRYSTAL_CAVES_LUKEWARM = keyOf("crystal_caves_lukewarm");
    public static final RegistryKey<Biome> CRYSTAL_CAVES_WARM = keyOf("crystal_caves_warm");
    public static final RegistryKey<Biome> DEEP_COOL_OCEAN = keyOf("deep_cool_ocean");
    public static final RegistryKey<Biome> DEEP_WARM_OCEAN = keyOf("deep_warm_ocean");
    public static final RegistryKey<Biome> DESERT_FIELDS = keyOf("desert_fields");
    //public static final RegistryKey<Biome> EBONY_THICKET = keyOf("ebony_thicket");
    public static final RegistryKey<Biome> ECHOING_HOLLOW = keyOf("echoing_hollow");
    public static final RegistryKey<Biome> ENCHANTED_FOREST = keyOf("enchanted_forest");
    public static final RegistryKey<Biome> FORGOTTEN_ISLES = keyOf("forgotten_isles");
    public static final RegistryKey<Biome> FOSSILIZED_DEPTHS = keyOf("fossilized_depths");
    public static final RegistryKey<Biome> FROSTBURN_CAVES = keyOf("frostburn_caves");
    public static final RegistryKey<Biome> FROSTED_TANGLE = keyOf("frosted_tangle");
    public static final RegistryKey<Biome> FROSTED_WOODLANDS = keyOf("frosted_woodlands");
    public static final RegistryKey<Biome> FROZEN_WETLANDS = keyOf("frozen_wetlands");
    public static final RegistryKey<Biome> FUNGAL_CHASM = keyOf("fungal_chasm");
    public static final RegistryKey<Biome> GLACIAL_SWEEP = keyOf("glacial_sweep");
    public static final RegistryKey<Biome> GLOWING_GROTTO = keyOf("glowing_grotto");
    public static final RegistryKey<Biome> GOLDEN_SWEEP = keyOf("golden_sweep");
    //public static final RegistryKey<Biome> GRASSLANDS = keyOf("grasslands");
    public static final RegistryKey<Biome> LAGOON = keyOf("lagoon");
    public static final RegistryKey<Biome> LAVENDER_FIELDS = keyOf("lavender_fields");
    public static final RegistryKey<Biome> LUKEWARM_RIVER = keyOf("lukewarm_river");
    public static final RegistryKey<Biome> LUSH_RIVER = keyOf("lush_river");
    public static final RegistryKey<Biome> MARSH = keyOf("marsh");
    public static final RegistryKey<Biome> MOLTEN_UNDERGROWTH = keyOf("molten_undergrowth");
    public static final RegistryKey<Biome> MONSOON_RAINFOREST = keyOf("monsoon_rainforest");
    public static final RegistryKey<Biome> MONTANE_CLEARING = keyOf("montane_clearing");
    public static final RegistryKey<Biome> MONTANE_WOODLANDS = keyOf("montane_woodlands");
    public static final RegistryKey<Biome> MUTED_TUNNELS = keyOf("muted_tunnels");
    public static final RegistryKey<Biome> OASIS = keyOf("oasis");
    public static final RegistryKey<Biome> OLD_GROWTH_SNOWY_TAIGA = keyOf("old_growth_snowy_taiga");
    public static final RegistryKey<Biome> PAINTED_BEACH = keyOf("painted_beach");
    public static final RegistryKey<Biome> PAINTED_PEAKS = keyOf("painted_peaks");
    public static final RegistryKey<Biome> PALE_UNDERGROWTH = keyOf("pale_undergrowth");
    public static final RegistryKey<Biome> PASTEL_CAVERNS = keyOf("pastel_caverns");
    public static final RegistryKey<Biome> PHANTOM_HOLLOW = keyOf("phantom_hollow");
    public static final RegistryKey<Biome> PINE_TAIGA = keyOf("pine_taiga");
    public static final RegistryKey<Biome> PRAIRIE = keyOf("prairie");
    public static final RegistryKey<Biome> RAINBOW_FIELDS = keyOf("rainbow_fields");
    public static final RegistryKey<Biome> REDWOOD_FOREST = keyOf("redwood_forest");
    public static final RegistryKey<Biome> SALT_MARSH = keyOf("salt_marsh");
    public static final RegistryKey<Biome> SALT_RIVER = keyOf("salt_river");
    public static final RegistryKey<Biome> SANDY_RIVER = keyOf("sandy_river");
    public static final RegistryKey<Biome> SHIMMERING_WASTELANDS = keyOf("shimmering_wastelands");
    public static final RegistryKey<Biome> SHRUBLANDS = keyOf("shrublands");
    public static final RegistryKey<Biome> SPECTRAL_ABYSS = keyOf("spectral_abyss");
    public static final RegistryKey<Biome> STEPPE = keyOf("steppe");
    public static final RegistryKey<Biome> SUBZERO_ABYSS = keyOf("subzero_abyss");
    public static final RegistryKey<Biome> SUNBAKED_PEAKS = keyOf("sunbaked_peaks");
    public static final RegistryKey<Biome> SUNBAKED_SHORE = keyOf("sunbaked_shore");
    public static final RegistryKey<Biome> TANGLED_TROPICS = keyOf("tangled_tropics");
    public static final RegistryKey<Biome> TOXIC_WASTES = keyOf("toxic_wastes");
    public static final RegistryKey<Biome> TROPICAL_BEACH = keyOf("tropical_beach");
    public static final RegistryKey<Biome> TROPICAL_RAINFOREST = keyOf("tropical_rainforest");
    public static final RegistryKey<Biome> TUNDRA = keyOf("tundra");
    public static final RegistryKey<Biome> VOLCANIC_PEAKS = keyOf("volcanic_peaks");
    public static final RegistryKey<Biome> WHIMSY = keyOf("whimsy");
    public static final RegistryKey<Biome> WINDSWEPT_TUNDRA = keyOf("windswept_tundra");
    public static final RegistryKey<Biome> WINTER_WONDERLAND = keyOf("winter_wonderland");

    public static RegistryKey<Biome> keyOf(String id) {
        return RegistryKey.of(RegistryKeys.BIOME, Identifier.of(WithersOverhaul.MOD_ID, id));
    }
}
